#! /bin/ash

#      -*- OpenSAF  -*-
#
#  Copyright (c) 2007, Ericsson AB
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  This
# file and program are licensed under High-Availability Operating 
# Environment Software License Version 1.4.
# Complete License can be accesseble from below location.
# http://www.opensaf.org/license 
# See the Copying file included with the OpenSAF distribution for
# full licensing terms.
#
# Author(s):
#   
#

cd /hostfs
ksize=12288
test -r isize && ksize=`cat isize`
dd if=/dev/zero of=root.img bs=1024 count=$ksize
mkfs.ext2 -F root.img
mkdir -p /mnt
mount -t ext2 -o loop root.img /mnt
cp -a root_template/* /mnt
if test -d root_extras; then
    cp -a root_extras/* /mnt
fi
makedevs -d /dev/MAKEDEVS /mnt
chown -R root:root /mnt
df /mnt > /hostfs/df-root_fs
umount /mnt
sync
halt -f
