#!/bin/ash
#
#      -*- OpenSAF  -*-
#
# (C) Copyright 2007 The OpenSAF Foundation
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
# under the GNU Lesser General Public License Version 2.1, February 1999.
# The complete license can be accessed from the following location:
# http://opensource.org/licenses/lgpl-license.php
# See the Copying file included with the OpenSAF distribution for full
# licensing terms.
#
# Author(s): Ericsson AB
#

cd /hostfs
ksize=12288
test -r isize && ksize=`cat isize`
dd if=/dev/zero of=root.img bs=1024 count=$ksize
mkfs.ext2 -F root.img
mkdir -p /mnt
mount -t ext2 -o loop root.img /mnt
cp -a root_template/* /mnt
if test -d root_extras; then
    cp -a root_extras/* /mnt
fi
makedevs -d /dev/MAKEDEVS /mnt
chown -R root:root /mnt
df /mnt > /hostfs/df-root_fs
umount /mnt
sync
halt -f
