#!/bin/bash
#
#      -*- OpenSAF  -*-
#
# (C) Copyright 2008-2016 The OpenSAF Foundation
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
# under the GNU Lesser General Public License Version 2.1, February 1999.
# The complete license can be accessed from the following location:
# http://opensource.org/licenses/lgpl-license.php
# See the Copying file included with the OpenSAF distribution for full
# licensing terms.
#
# Author(s): Ericsson AB
#

# UML System startup script

die() {
	echo "ERROR: $*"
	exit 1
}

wait_for_pid_to_start() {
	pid=$1
	while ! test -d /proc/$pid; do sleep 0.1; done
}

wait_for_pid_to_die() {
	pid=$1
	while test -d /proc/$pid; do sleep 0.1; done
}

test -f "$PWD/$0" || die "Must execute $0 from directory where it is located"

dir=$(dirname "$0"); dir=$(cd "$dir"; pwd)
build=${OSAF_UML_BUILD:-$dir/uml}
export OSAF_UML_BUILD=$build

export CLUSTER_SIM_UML_DIR=$PWD
export PATH=$build/bin:${PWD}/uml/bin:${PATH}
test \( \! -d ./rootfs \) -a \( "$1" != "stop" -a "$1" != "clean" \) && die "No shadow root at [./rootfs]"

UML_DIR=$CLUSTER_SIM_UML_DIR/uml
REPL_DIR=repl-opensaf
test -x "$UML_DIR/bin/uml_start" || die "Not executable [$UML_DIR/bin/uml_start]"

if test -d ./rootfs; then
    immxml_sc_count=$(grep -c 'SC SC-' ./rootfs/usr/local/share/opensaf/immxml/nodes.cfg)
    immxml_pl_count=$(grep -c 'PL PL-' ./rootfs/usr/local/share/opensaf/immxml/nodes.cfg)
    immxml_node_count=$((immxml_sc_count + immxml_pl_count))
    NUMNODES=${2:-$immxml_node_count}
fi
OSAF_UML_MAX_TERMS=${OSAF_UML_MAX_TERMS:-5}
IPADDRBASE=${IPADDRBASE:-192.168}
PIDFILEDIR=/tmp/${USER}_opensaf
OSAF_UML_MEMSIZE=${OSAF_UML_MEMSIZE:-128M}
uid=$(id -u)

check_binaries() {
    for i in tipc busybox linux uml_switch port-helper tunctl uml_mconsole uml_net; do
	test -x "$build/bin/$i" || die "Not executable [$build/bin/$i]"
    done
}

cluster_start() {
	numnodes=$1
	x=65
	y=24
	dy=293

	echo "Starting opensaf services"

	# Clean-up
	rm -rf $PIDFILEDIR
	mkdir $PIDFILEDIR

	if ! test -d $CLUSTER_SIM_UML_DIR/$REPL_DIR; then
		mkdir -p $CLUSTER_SIM_UML_DIR/$REPL_DIR/immsv_store
		cp  rootfs/etc/opensaf/imm.xml \
			$CLUSTER_SIM_UML_DIR/$REPL_DIR/immsv_store/imm.xml
	fi

	# Create /etc/hosts file
	echo "127.0.0.1       localhost" > rootfs/etc/hosts

	# Start network if necessary
	if ! pgrep -U $uid uml_switch > /dev/null; then

		rm -f /tmp/uml-${uid}.ctl
		xterm -iconic -geometry 60x8-0+5 \
			-T UML-network -e $build/bin/uml_switch -unix /tmp/uml-${uid}.ctl $tap &
		echo $! > $PIDFILEDIR/uml_switch
		while [ ! -S /tmp/uml-${uid}.ctl ]; do
			sleep 0.1
		done
	fi

	# Start the processors
	node_name_prefix=SC-
	rootdir=rootfs
	for ((p=1; p <= $numnodes; p++)); do
		# First two nodes are system controllers, the rest are payloads
		if ((p == 3)); then
			x=910
			y=24
		fi
		if ((p > immxml_sc_count)); then
			node_name_prefix=PL-
		fi
		hostname=$node_name_prefix$p
		if [ $p -le $OSAF_UML_MAX_TERMS ]; then
			xterm -hold -geometry 140x20+$x+$y -T $hostname -e \
				$UML_DIR/bin/uml_start $p umid=$hostname mem=${OSAF_UML_MEMSIZE} hostname=$hostname shadowroot=$rootdir $$ &
			echo $! > $PIDFILEDIR/$hostname
		else
			$UML_DIR/bin/uml_start $p umid=$hostname mem=${OSAF_UML_MEMSIZE} hostname=$hostname shadowroot=$rootdir $$ < /dev/null >& /dev/null &
			echo $! > $PIDFILEDIR/$hostname
		fi
		y=$((y+dy))

		# Append host to /etc/hosts file
		echo "$IPADDRBASE.$((p / 256)).$((p % 256))       $hostname.opensaf.org  $hostname" >> rootfs/etc/hosts
	done

	node_name_prefix=SC-
	for ((p=1; p <= $numnodes; p++)); do
		if ((p > immxml_sc_count)); then
			node_name_prefix=PL-
		fi
		while ! test -f $HOME/.uml/$hostname/pid ; do sleep 0.1; done
		pid=$(cat $HOME/.uml/$hostname/pid)
		wait_for_pid_to_start $pid
	done
}

cluster_stop() {
	echo "Stopping opensaf services"
 	nodes=$(ls -1 "$HOME/.uml")
	for node in $nodes; do
		pid=$(cat $HOME/.uml/$node/pid)
		"$build/bin/uml_mconsole" "$node" halt > /dev/null 2>&1
		wait_for_pid_to_die $pid
	done
	for node in $nodes; do
 		rm -rf "$HOME/.uml/$node"
	done
	if [ -d $PIDFILEDIR ]; then
		pidfiles=$(ls $PIDFILEDIR)
		for pidfile in $pidfiles; do
			pid=$(cat $PIDFILEDIR/$pidfile)
			kill -9 $pid > /dev/null 2>&1
			wait_for_pid_to_die $pid
		done
		rm -rf $PIDFILEDIR
	fi
	pkill -9 -U $uid uml_switch
	rm -f /tmp/uml-${uid}.ctl
}

delete_persistent_store() {
	echo "Deleting persistent store contents"
	rm -rf $CLUSTER_SIM_UML_DIR/rootfs/var/*
	rm -rf $CLUSTER_SIM_UML_DIR/$REPL_DIR
}

# Stop a single node, referenced by number
node_stop() {
	if [ $1 -le $immxml_sc_count ]; then
		node="SC-$1"
	else
		node="PL-$1"
	fi

	if ls $HOME/.uml/$node/pid &> /dev/null; then
		echo "Stopping node $node"
	else
		die "Node $1 is not started"
	fi
	pid=$(cat $HOME/.uml/$node/pid)

	# halt the uml vm
	$build/bin/uml_mconsole $node halt > /dev/null 2>&1
	wait_for_pid_to_die $pid
	rm -rf $HOME/.uml/$node

	# kill the xterm
	pid=$(cat $PIDFILEDIR/$node)
	kill -9 $pid > /dev/null 2>&1
	wait_for_pid_to_die $pid
	rm $PIDFILEDIR/$node
}

# Start a single node, referenced by number
node_start() {
	node=$1
	dy=293
	p=$node

	if ((p <= immxml_sc_count)); then
		node_name_prefix=SC-
	else
		node_name_prefix=PL-
	fi

	hostname=$node_name_prefix$p

	test -d $PIDFILEDIR || mkdir -p $PIDFILEDIR

	if ls $HOME/.uml/$hostname/pid &> /dev/null; then
		node_stop $node
	fi

	if ! test -d $CLUSTER_SIM_UML_DIR/$REPL_DIR; then
		mkdir -p $CLUSTER_SIM_UML_DIR/$REPL_DIR/immsv_store
		cp  rootfs/etc/opensaf/imm.xml \
			$CLUSTER_SIM_UML_DIR/$REPL_DIR/immsv_store/imm.xml
	fi

	# Start network if necessary
	if ! pgrep -U $uid uml_switch > /dev/null; then
		rm -f /tmp/uml-${uid}.ctl
		xterm -iconic -geometry 60x8-0+5 \
			-T UML-network -e $build/bin/uml_switch -unix /tmp/uml-${uid}.ctl $tap &
		echo $! > $PIDFILEDIR/uml_switch
		while [ ! -S /tmp/uml-${uid}.ctl ]; do
			sleep 0.1
		done
	fi

	if ! stat "rootfs/etc/hosts" &> /dev/null; then
		echo "127.0.0.1       localhost" > rootfs/etc/hosts
	fi

	echo "Starting node $node"

	rootdir=rootfs

	# start the uml vm in its own xterm
	x=$((p < 3 ? 65 : 910))
	y=$((24 + (p < 3 ? p - 1 : p - 3) * dy))
	xterm -hold -geometry 140x20+$x+$y -T $hostname -e \
		$UML_DIR/bin/uml_start $p umid=$hostname mem=${OSAF_UML_MEMSIZE} hostname=$hostname shadowroot=$rootdir $$ &
	echo $! > $PIDFILEDIR/$hostname

	# Append host to /etc/hosts file
	grep -q "$hostname.opensaf.org" rootfs/etc/hosts || echo "$IPADDRBASE.$((p / 256)).$((p % 256))       $hostname.opensaf.org  $hostname" >> rootfs/etc/hosts

	while ! test -f $HOME/.uml/$hostname/pid ; do sleep 0.1; done
	pid=$(cat $HOME/.uml/$hostname/pid)
	wait_for_pid_to_start $pid
}

case "$1" in
	start)
		check_binaries
		cluster_stop
		cluster_start $NUMNODES
		;;
	stop)
		cluster_stop
		;;
	nodestart)
		test $# -eq 2 || die "wrong number of arguments"
		check_binaries
		node_start $2
		;;
	nodestop)
		test $# -eq 2 || die "wrong number of arguments"
		node_stop $2
		;;
	clean)
		delete_persistent_store
		;;
	*)
		echo "Usage: $0 {start [numnodes] | stop | nodestart <number> | nodestop <number> | clean}"
		exit 1
esac
exit 0
