#!/bin/ash
#
#      -*- OpenSAF  -*-
#
# (C) Copyright 2010 The OpenSAF Foundation
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
# under the GNU Lesser General Public License Version 2.1, February 1999.
# The complete license can be accessed from the following location:
# http://opensource.org/licenses/lgpl-license.php
# See the Copying file included with the OpenSAF distribution for full
# licensing terms.
#
# Author(s): Ericsson AB
#

die() {
    echo "ERROR: $*" >&2
    exit 1
}

test -n "$1" || die "Target missing"
adr=$1
shift
test -n "$1" || die "Command missing"
qstr=$(echo "$@" | tr -s ' ' '+')
wget -Y off -q -O - http://$adr/cgi-bin/rshd?$qstr > $tmp/exec 2>&1
eval $(grep '^EXITSTATUS=' $tmp/exec)
grep -v '^EXITSTATUS=' $tmp/exec
return $EXITSTATUS
