/*      -*- OpenSAF  -*-
 *
 * (C) Copyright 2008 The OpenSAF Foundation 
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
 * under the GNU Lesser General Public License Version 2.1, February 1999.
 * The complete license can be accessed from the following location:
 * http://opensource.org/licenses/lgpl-license.php 
 * See the Copying file included with the OpenSAF distribution for full
 * licensing terms.
 *
 * Author(s): Emerson Network Power
 *   
 */

/*****************************************************************************
..............................................................................
  
  ..............................................................................
 
  DESCRIPTION:This module deals wih registering AvM with MDS and provides the
  callbacks for MDS .
  ..............................................................................

  Function Included in this Module:

  ncsavmscalars_set     -
  ncsavmscalars_get     -
  ncsavmscalars_extract -
  ncsavmscalars_setrow  -
  ncsavmscalars_next    -
******************************************************************************
*/
#include "avm.h"

/*****************************************************************************
 * Function: ncsavmscalars_get
 *
 * Purpose:  This function is one of the get processing routines for 
*            objects in NCSMIB_TBL_AVM_ENT_DEPLOYMENT table. 
 * The name of this function is generated by the MIBLIB tool. 
 * will be called by MIBLIB after validating the arg information.
 * This function finds the corresponding data structure for the given
 * instance and returns the pointer to the structure.
 *
 * Input:  cb        - AVD control block.
 *         arg       - The pointer to the MIB arg that was provided by the caller.
 *         data      - The pointer to the data-structure containing the object
 *                     value is returned by reference.
 *
 * Returns: The status returned by the operation. MIB lib will use it
 *                   to set the args->rsp.i_status field before returning the
 *                   NCSMIB_ARG to the caller's context
 * NOTES: This function works in conjunction with extract function to provide the
 * get functionality.
 *
 * 
 **************************************************************************/
EXTERN_C uns32 
ncsavmscalars_get( NCSCONTEXT     cb, 
                   NCSMIB_ARG    *arg, 
                   NCSCONTEXT    *data
                 )
{
   AVM_CB_T *avm_cb = (AVM_CB_T*)cb;
   
   *data = (NCSCONTEXT*)avm_cb;
   
   return NCSCC_RC_SUCCESS;
}

EXTERN_C uns32 
ncsavmscalars_extract(NCSMIB_PARAM_VAL *param, 
                      NCSMIB_VAR_INFO  *var_info, 
                      NCSCONTEXT        data,
                      NCSCONTEXT        buffer
                     )
{
   AVM_CB_T *cb = (AVM_CB_T*)data;
   uns32    rc;
   
   if(AVM_CB_NULL == cb)
   {
      return NCSCC_RC_NO_INSTANCE;
   }
   
   switch(param->i_param_id)
   {
      case ncsAvmAdmSwitch_ID:
      {
         param->i_fmat_id  = NCSMIB_FMAT_INT;
         param->i_length   = 1;
         param->info.i_int = (cb->adm_switch == TRUE)? TRUE : FALSE;
         rc = NCSCC_RC_SUCCESS;
      }
      break;  

      default:
      {
         rc = NCSCC_RC_NO_OBJECT;
      }
   }
   
   return rc;
}

/*****************************************************************************
 * Function: ncsavmscalars_set
 *
 * Purpose:  This function is the set processing for objects in
 * NCSMIB_TBL_AVM_ENT_DEPLOYMENT table. This is the Deployed Entities table. The
 * name of this function is generated by the MIBLIB tool. This function
 * will be called by MIBLIB after validating the arg information.
 * This function does the set of the object and the corresponding 
 * actions  for the objects that are settable. 
 * This same function can be used for test  operation also.
 *
 * Input:  cb        - AvM control block
 *         arg       - The pointer to the MIB arg that was provided by  
 *                     the caller.
 *         var_info  - The VAR INFO structure pointer generated by MIBL 
 *                     IB for  the objects in this table.
 *         test_flag - The flag that indicates if this is set or test.
 *
 * Returns: The status returned by the operation. MIB lib will use it
 *          to set the args->rsp.i_status field before returning the
 *          NCSMIB_ARG to the caller's context.
 *
 * NOTES: None.
 *
 * 
 *****************************************************************************/
EXTERN_C uns32 
ncsavmscalars_set(NCSCONTEXT         cb, 
                  NCSMIB_ARG        *arg, 
                  NCSMIB_VAR_INFO   *var_info, 
                  NCS_BOOL           test_flag
                 )
{
   AVM_CB_T   *avm_cb = AVM_CB_NULL;
   AVM_EVT_T   evt;

   avm_cb = (AVM_CB_T*)cb; 
   
   if(SA_AMF_HA_ACTIVE != avm_cb->ha_state)
   {
      return NCSCC_RC_INV_VAL;
   }

   if(TRUE == test_flag)
   {
      return NCSCC_RC_SUCCESS;
   }
   
   switch(arg->req.info.set_req.i_param_val.i_param_id)
   {
      case ncsAvmAdmSwitch_ID:
      {
         evt.fsm_evt_type = AVM_ROLE_EVT_ADM_SWITCH;
         avm_role_fsm_handler(cb, &evt);
      }
      break;

      default:
      {
         m_AVM_LOG_INVALID_VAL_FATAL(arg->req.info.set_req.i_param_val.i_param_id);
         return NCSCC_RC_FAILURE;
      }
   }

   return NCSCC_RC_SUCCESS;
}

EXTERN_C uns32 
ncsavmscalars_next(NCSCONTEXT        cb, 
                   NCSMIB_ARG       *arg, 
                   NCSCONTEXT       *data, 
                   uns32            *next_inst_id,
                   uns32            *next_inst_id_len)
{
   /* Invalid Instance */
   return NCSCC_RC_NO_INSTANCE;
}

EXTERN_C uns32 
ncsavmscalars_setrow(NCSCONTEXT               cb, 
                     NCSMIB_ARG              *args,
                     NCSMIB_SETROW_PARAM_VAL *params,
                     struct ncsmib_obj_info  *obj_info,
                     NCS_BOOL                 testrow_flag)
{
   return NCSCC_RC_SUCCESS;
}
