/*
 * This Java file has been generated by smidump 0.3.0. It
 * is intended to be edited by the application programmer and
 * to be used within a Java AgentX sub-agent environment.
 *
 * $Id: InterfacesImpl.java,v 1.11 2002/03/05 14:27:09 strauss Exp $
 */

/**
    This class extends the Java AgentX (JAX) implementation of
    the scalar group interfaces defined in IF-MIB.
 */

import java.util.Vector;
import java.util.Enumeration;
import jax.AgentXOID;
import jax.AgentXSetPhase;
import jax.AgentXResponsePDU;

public class InterfacesImpl extends Interfaces
{

    public int get_ifNumber()
    {
        return ifNumber;
    }

}

