/*
 * This Java file has been generated by smidump 0.3.0. Do not edit!
 * It is intended to be used within a Java AgentX sub-agent environment.
 *
 * $Id: WarmStart.java,v 1.11 2002/03/05 14:27:10 strauss Exp $
 */

import jax.AgentXOID;
import jax.AgentXVarBind;
import jax.AgentXNotification;
import java.util.Vector;

public class WarmStart extends AgentXNotification
{

    private final static long[] warmStart_OID = {1, 3, 6, 1, 6, 3, 1, 1, 5, 2};
    private static AgentXVarBind snmpTrapOID_VarBind =
        new AgentXVarBind(snmpTrapOID_OID,
                          AgentXVarBind.OBJECTIDENTIFIER,
                          new AgentXOID(warmStart_OID));



    public WarmStart() {
        AgentXOID oid;
        AgentXVarBind varBind;

        // add the snmpTrapOID object
        varBindList.addElement(snmpTrapOID_VarBind);
    }

    public Vector getVarBindList() {
        return varBindList;
    }

}

