/*      -*- OpenSAF  -*-
 *
 * (C) Copyright 2008 The OpenSAF Foundation
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
 * under the GNU Lesser General Public License Version 2.1, February 1999.
 * The complete license can be accessed from the following location:
 * http://opensource.org/licenses/lgpl-license.php
 * See the Copying file included with the OpenSAF distribution for full
 * licensing terms.
 *
 * Author(s): Emerson Network Power
 *
 */

/*****************************************************************************
..............................................................................
  DESCRIPTION:

  This module contains logging/tracing constants used in MASv.

******************************************************************************
*/

/*
 * Module Inclusion Control...
 */
#ifndef MAB_LOG_CONST_H
#define MAB_LOG_CONST_H

#include "gl_defs.h"
#include "ncs_lib.h"
#include "mab_penv.h"

/*****************************************************************************
  MAB_LOG_INST    A common "base class" used during logging for every 
                  MAB component(MAA/MAS/OAA).
*****************************************************************************/

typedef struct mab_log_inst
  {
  /* Configuration Objects */

  uns32           log_bits;    /* RW bitmap of log categories to install   */
  NCS_BOOL         log_enbl;    /* RW ENABLE|DISABLE logging                */

  } MAB_LOG_INST;


/*******************************************************************************************/

/******************************************************************************
 Logging offset indexes for Headline logging
 ******************************************************************************/

typedef enum MAB_hdln_flex
  {
    MAB_HDLN_MAC_CREATE_SUCCESS,
    MAB_HDLN_MAC_VALID_MIB_REQ_RCVD,
    MAB_HDLN_MAC_INVALID_MIB_REQ_RCVD,
    MAB_HDLN_MAC_FRWD_MIB_REQ_TO_MAS,
    MAB_HDLN_MAC_NO_MAS_FRWD,
    MAB_HDLN_MAC_PUSH_BTSE_SUCCESS,
    MAB_HDLN_MAC_PUSH_BTSE_FAILED,
    MAB_HDLN_MAC_NULL_MIB_RSP_RCVD,
    MAB_HDLN_MAC_INVALID_MIB_RSP_RCVD, 
    MAB_HDLN_MAC_USR_RSP_FNC_RET,
    MAB_HDLN_MAC_PLAYBACK_IN_PROGRESS,
    MAB_HDLN_MAC_RCVD_INVALID_OP,
    MAB_HDLN_MAC_INVALID_KEYS_RSP_FUNC, 
    MAB_HDLN_MAC_PUSH_ORIG_FAILED, 
    MAB_HDLN_MAC_POP_ORIG_FAILED,
    MAB_HDLN_MAC_POP_NOT_MIB_ORIG,
    MAB_HDLN_MAC_MIBARG_FREE_FAILED, 
    MAB_HDLN_MAC_INSTANTIATE_SUCCESS, 
    MAB_HDLN_MAC_UNINSTANTIATE_SUCCESS, 
    MAB_HDLN_MAC_ENV_INST_NOT_FOUND, 
    MAB_HDLN_MAC_ENV_INST_ADD_SUCCESS, 
    MAB_HDLN_MAC_ENV_INST_REL_SUCCESS, 
    MAB_HDLN_MAC_LOG_MDS_ENC_FAILURE,
    MAB_HDLN_MAC_LOG_MDS_DEC_FAILURE,

    MAB_HDLN_MAS_CREATE_SUCCESS,
    MAB_HDLN_MAS_DESTROY_SUCCESS,
    MAB_HDLN_MAS_FIND_OAC_FAILED, 
    MAB_HDLN_MAS_FIND_OAC_SUCCESS,
    MAB_HDLN_MAS_SNT_NO_INST_RSP, 
    MAB_HDLN_MAS_PUSH_FISE_SUCCESS,
    MAB_HDLN_MAS_PUSH_FISE_FAILED, 
    MAB_HDLN_MAS_PUSH_BTSE_SUCCESS, 
    MAB_HDLN_MAS_PUSH_BTSE_FAILED,
    MAB_HDLN_MAS_FRWD_MIB_REQ_TO_OAC,
    MAB_HDLN_MAS_NO_OAC_FRWD,
    MAB_HDLN_MAS_POP_FISE_SUCCESS,
    MAB_HDLN_MAS_POP_BTSE_SUCCESS,
    MAB_HDLN_MAS_POP_SE_FAILED,
    MAB_HDLN_MAS_POP_XSE, 
    MAB_HDLN_MAS_RCV_NI_MIB_RSP, 
    MAB_HDLN_MAS_FRWD_NI_RSP_TO_MAC,
    MAB_HDLN_MAS_RCV_OK_MIB_RSP,
    MAB_HDLN_MAS_FRWD_OK_RSP_TO_MAC,
    MAB_HDLN_MAS_NO_OK_FRWD_TO_MAC,
    MAB_HDLN_MAS_RCV_X_MIB_RSP, 
    MAB_HDLN_MAS_RCV_XSTAT_MIB_RSP,  
    MAB_HDLN_MAS_RCV_X_FLTR_REG_REQ,
    MAB_NEW_TBL_ROW_REC_SUCCESS,
    MAB_NEW_MAS_FLTR_FAILED, 
    MAB_NEW_MAS_FLTR_SUCCESS,
    MAB_HDLN_MAS_OAA_DOWN,
    MAB_HDLN_MAS_RCVD_INVALID_OP,
    MAB_HDLN_MAS_AMF_INITIALIZE_SUCCESS,
    MAB_HDLN_MAS_AMF_HLTH_DOING_AWESOME,
    MAB_HDLN_MAS_AMF_CSI_DETAILS,
    MAB_HDLN_MAS_AMF_CSI_DESC_DETAILS, 
    MAB_HDLN_MAS_AMF_CSI_STATE_CHG_FAILED, 
    MAB_HDLN_MAS_AMF_CSI_STATE_CHG_SUCCESS, 
    MAB_HDLN_MAS_FLTR_INVALID_RANGES, 
    MAB_HDLN_MAS_FLTR_SA_NO_OAA, 
    MAB_HDLN_MAS_IDX_RECEVD, 
    MAB_HDLN_MAS_AMF_HLTH_DOING_AWFUL,
    MAB_HDLN_MAS_DEF_ENV_INIT_SUCCESS,
    MAB_HDLN_MAS_CSI_REMOVE_SUCCESS, 
    MAB_HDLN_MAS_AMF_CSI_REMOVE_ALL_SUCCESS, 
    MAB_HDLN_MAS_CSI_ADD_ONE_SUCCESS, 
    MAB_HDLN_MAS_AMF_CSI_ATTRIB_DECODE_SUCCESS,
    MAB_HDLN_MAS_FRWD_MOVEROW_MIB_REQ_TO_OAC,
    MAB_HDLN_MAS_MOVEROW_POP_XSE,
    MAB_HDLN_MAS_MOVEROW_RSP_FAILED,
    MAB_HDLN_MAS_MOVEROW_RSP_SUCCESS,
    MAB_HDLN_MAS_POP_FISE_FAILED, 
    MAB_HDLN_MAS_FRWD_MIB_REQ_TO_THIS_OAC, 
    MAB_HDLN_MAS_FLTRS_FLUSH, 
    MAB_HDLN_MAS_OAA_ADDR, 
    MAB_HDLN_MAS_MBCSV_INTF_INIT_SUCCESS,
    MAB_HDLN_MAS_MBCSV_ENC,
    MAB_HDLN_MAS_MBCSV_DEC,
    MAB_HDLN_MAS_COLD_SYNC_DEC_SUCCESS,
    MAB_HDLN_MAS_COLD_SYNC_ENC_COMPL, 
    MAB_HDLN_MAS_COLD_SYNC_ENC_BKT,
    MAB_HDLN_MAS_COLD_SYNC_DEC_COMPL,
    MAB_HDLN_MAS_ASYNC_COUNT_ENC,
    MAB_HDLN_MAS_ASYNC_COUNT_DEC,
    MAB_HDLN_MAS_ASYNC_COUNT_SBY,
    MAB_HDLN_SBY_OUT_OF_SYNC,
    MAB_HDLN_MAS_SBY_IN_SYNC,
    MAB_HDLN_MBCSV_ERR_IND_AMF_ERR_REPORT,
    MAB_HDLN_MAS_MBCSV_DATARSP_CMPLT, 
    MAB_HDLN_MAS_MBCSV_ASYNC_UPDT_SUCCESS,
    MAB_HDLN_MAS_CSI_INSTALL_SUCCESS,
    MAB_HDLN_MAS_DEF_CSI_SUCCESS,
    MAB_HDLN_AMF_RESPONSE_POSTPONED, 
    MAB_HDLN_AMF_SBY_RESPONSE_SENT, 
    MAB_HDLN_MAS_DUP_DEF_FLTR, 
    MAB_HDLN_MAS_MDS_DEST,
    MAB_HDLN_MAS_VERSION, 
    MAB_HDLN_MAS_LOG_MDS_ENC_FAILURE,
    MAB_HDLN_MAS_LOG_MDS_DEC_FAILURE,
    MAB_HDLN_MAS_MBCSV_ENC_FAILURE,
    MAB_HDLN_MAS_MBCSV_DEC_FAILURE,

    MAB_HDLN_OAC_CREATE_SUCCESS,
    MAB_HDLN_OAC_TBL_EXISTS,
    MAB_HDLN_OAC_NEW_TBL_SUCCESS,
    MAB_HDLN_OAC_REGD_TBL,
    MAB_HDLN_OAC_NO_TBL_TO_UNREG,
    MAB_HDLN_OAC_SCHD_UNREG_FLTR_OK,
    MAB_HDLN_OAC_SCHD_UNREG_FLTR_NOT,
    MAB_HDLN_OAC_DEL_TBL_REC_SUCCESS,
    MAB_HDLN_OAC_DEL_TBL_REC_FAILED,
    MAB_HDLN_OAC_SCHD_DEL_TBL_REC, 
    MAB_HDLN_OAC_UNREGD_TBL,
    MAB_HDLN_OAC_FLTR_REG_SOON_NO_TBL,
    MAB_HDLN_OAC_REG_WRONG_FLTR_TYPE,
    MAB_HDLN_OAC_NEW_FLTR_SUCCESS,
    MAB_HDLN_OAC_NEW_FLTR_FAILED,
    MAB_HDLN_OAC_FRWD_FLTR_REG_TO_MAS,
    MAB_HDLN_OAC_NO_FRWD_REG_TO_MAS,
    MAB_HDLN_OAC_REGD_MAB_FLTR,
    MAB_HDLN_OAC_TBL_DEL_SCHDD,
    MAB_HDLN_OAC_NO_FLTRS_TO_UNREG,
    MAB_HDLN_OAC_FIND_FLTR_FAILED,
    MAB_HDLN_OAC_FIND_FLTR_SUCCESS,
    MAB_HDLN_OAC_FRWD_FLTR_UNREG,
    MAB_HDLN_OAC_NO_FRWD_UNREG, 
    MAB_HDLN_OAC_UNREGD_MAB_FLTR,
    MAB_HDLN_OAC_SNT_FLTR_TO_MAS,
    MAB_HDLN_OAC_SCHD_FLTR_RESEND,
    MAB_HDLN_OAC_POP_BTSE_SUCCESS,
    MAB_HDLN_OAC_POP_SE_FAILED,
    MAB_HDLN_OAC_POP_XSE,
    MAB_HDLN_OAC_FRWD_RSP_SUCCESS,
    MAB_HDLN_OAC_FRWD_PSR_FAILED,
    MAB_HDLN_OAC_MIB_REQ_FAILED,
    MAB_HDLN_OAC_MIB_REQ_SUCCESS,
    MAB_HDLN_OAC_PUSH_FLAG_FAILED,
    MAB_HDLN_OAC_POP_FLAG_FAILED,
    MAB_HDLN_OAC_POP_FLAG_SUCCESS,
    MAB_HDLN_OAC_SENDTO_PSR_SUCCESS,
    MAB_HDLN_OAC_SENDTO_PSR_FAILED,
    MAB_HDLN_OAC_NULL_MIB_RSP_RCVD, 
    MAB_HDLN_OAC_INVALID_MIB_RSP_RCVD, 
    MAB_HDLN_OAC_USR_RSP_FNC_RET,
    MAB_HDLN_OAC_SU_CBK_FAILED,
    MAB_HDLN_OAC_MIBARG_FREE_FAILED,
    MAB_HDLN_OAC_RCVD_INVALID_OP, 
    MAB_HDLN_OAC_INSTANTIATE_SUCCESS, 
    MAB_HDLN_OAC_UNINSTANTIATE_SUCCESS, 
    MAB_HDLN_OAC_ENV_INST_NOT_FOUND, 
    MAB_HDLN_OAC_ENV_INST_ADD_SUCCESS, 
    MAB_HDLN_OAC_ENV_INST_REL_SUCCESS, 
    MAB_HDLN_OAC_PCN_LIST_ADD_FAIL,
    MAB_HDLN_OAC_ADD_WBREQ_TO_PEND_LIST_FAIL,
    MAB_HDLN_OAC_CONVRT_WBREQ_TO_MAB_MSG_FAIL,
    MAB_HDLN_OAC_INVLD_PCN_IN_TBL_REG,
    MAB_HDLN_OAC_INVLD_PCN_IN_WARMBOOT_REQ,
    MAB_HDLN_OAC_PCN_OF_WARMBOOT_REQ_NOT_IN_PCN_LIST,
    MAB_HDLN_OAC_WARMBOOT_REQ_SEND_SUCCESS,
    MAB_HDLN_OAC_WARMBOOT_REQ_TO_PSS_MDS_SEND_FAIL,
    MAB_HDLN_OAC_WARMBOOT_REQ_REJECTED_DUE_TO_INVALID_TBLS_SPCFD,
    MAB_HDLN_NO_CB,
    MAB_HDLN_OAC_MAS_MDS_UP,
    MAB_HDLN_OAC_MAS_MDS_DOWN,
    MAB_HDLN_OAC_PSS_MDS_UP,
    MAB_HDLN_OAC_PSS_MDS_DOWN,
    MAB_HDLN_OAC_PSS_MDS_NO_ACTIVE,
    MAB_HDLN_OAC_PSS_MDS_NEW_ACTIVE,
    MAB_HDLN_OAC_PSS_MDS_NEW_ACTIVE_AS_UP_EVT,
    MAB_HDLN_OAA_PCN_NULL_IN_OAC_FINDADD_PCN_IN_LIST_FUNC,
    MAB_HDLN_OAC_INVOKING_SEND_BIND_REQ_TO_PSS,
    MAB_HDLN_OAC_INVOKING_SEND_WARMBOOT_REQ_TO_PSS,
    MAB_HDLN_OAC_TERMINATING_WARMBOOT_REQ_API_PROCESSING,
    MAB_HDLN_OAC_BIND_REQ_TO_PSS_SND_SUCCESS,
    MAB_HDLN_OAC_BIND_REQ_TO_PSS_SND_FAIL, 
    MAB_HDLN_OAC_UNBIND_REQ_TO_PSS_SND_SUCCESS,
    MAB_HDLN_OAC_UNBIND_REQ_TO_PSS_SND_FAIL, 
    MAB_HDLN_ACK_FRM_PSS_RCVD,
    MAB_HDLN_EOP_STATUS_FOR_HDL_RCVD,
    MAB_HDLN_INVKNG_EOP_STATUS_CB_FOR_USR,
    MAB_HDLN_INVKD_EOP_STATUS_CB_FOR_USR,
    MAB_HDLN_INV_BUFZONE_EVT_TYPE,
    MAB_HDLN_BUFZONE_NODE_ALLOC_FAIL,
    MAB_HDLN_BUFZONE_SNMP_DUP_FAILED,
    MAB_HDLN_BUFZONE_NODE_ADDED, 
    MAB_HDLN_BUFZONE_NODE_REMOVED,
    MAB_HDLN_OAC_BUFR_ZONE_EVT_SEND_SUCCESS,
    MAB_HDLN_OAC_BUFR_ZONE_EVT_SEND_FAIL,

    MAB_HDLN_RDA_GIVEN_INIT_ROLE,
    MAB_HDLN_OAC_MAS_MDS_NO_ACTIVE,
    MAB_HDLN_OAC_MAS_MDS_NEW_ACTIVE,
    MAB_HDLN_OAC_MAS_MDS_NEW_ACTIVE_AS_UP_EVT,
    MAB_HDLN_IGNORING_NON_PRIMARY_MDS_SVC_EVT,
    MAB_HDLN_OAC_LOG_MDS_ENC_FAILURE,
    MAB_HDLN_OAC_LOG_MDS_DEC_FAILURE,
    MAB_HDLN_MAS_ANCHR_FLTR_PAIR,

    MAB_HDLN_MAX
  } MAB_HDLN_FLEX;

  typedef enum mab_table_details
  {
      MAB_MAS_FIND_REQ_TBL_FAILED, 
      MAB_MAS_FIND_REQ_TBL_SUCCESS, 
      MAB_MAS_RCV_SA_FLTR_REG_REQ,
      MAB_MAS_RCV_ANY_FLTR_REG_REQ,
      MAB_MAS_RCV_RNG_FLTR_REG_REQ,
      MAB_MAS_RCV_RNG_FLTR_MIN_IDX, 
      MAB_MAS_RCV_RNG_FLTR_MAX_IDX, 
      MAB_MAS_RCV_DEF_FLTR_REG_REQ,
      MAB_MAS_FLTR_SA_NO_DST_TBL,
      MAB_MAS_FLTR_SA_EMPTY_DST_TBL,
      MAB_MAS_FLTR_SA_BAD_DST_TBL,
      MAB_MAS_RMV_ROW_REC_FAILED,
      MAB_MAS_RMV_ROW_REC_SUCCESS,
      MAB_OAC_FLTR_REG_NO_TBL,
      MAB_OAC_RMV_ROW_REC_SUCCESS,
      MAB_MAS_RCV_EXACT_FLTR_REG_REQ, 
      MAB_MAS_RCV_EXACT_FLTR_IDX,
      MAB_MAS_TABLE_DETAILS_MAX
  }MAB_TABLE_DETAILS; 

  typedef enum mab_fltr_details
  {
      MAB_MAS_FLTR_FIND_FAILED, 
      MAB_MAS_FLTR_FIND_SUCCESS,
      MAB_MAS_FLTR_RMV_FAILED,
      MAB_MAS_FLTR_RMV_SUCCESS,
      MAB_OAC_FLTR_RMV_SUCCESS, 
      MAB_OAC_FLTR_RMV_FAILED, 
      MAB_MAS_FLTR_MAX
  }MAB_FLTR_DETAILS; 

/******************************************************************************
 Logging offset indexes for Service Provider (MDS) logging
 ******************************************************************************/

typedef enum MAB_svc_prvdr_flex
  {
    MAB_SP_MAC_MDS_INSTALL_FAILED,
    MAB_SP_MAC_MDS_INSTALL_SUCCESS,
    MAB_SP_MAC_MDS_UNINSTALL_FAILED,
    MAB_SP_MAC_MDS_UNINSTALL_SUCCESS,
    MAB_SP_MAC_MDS_SUBSCR_FAILED,
    MAB_SP_MAC_MDS_SUBSCR_SUCCESS,
    MAB_SP_MAC_MDS_SND_MSG_FAILED,
    MAB_SP_MAC_MDS_RCV_MSG,
    MAB_SP_MAC_MDS_RCV_EVT,
    MAB_SP_MAC_MDS_CBINFO_NULL,

    MAB_SP_MAS_MDS_INSTALL_FAILED,
    MAB_SP_MAS_MDS_INSTALL_SUCCESS,
    MAB_SP_MAS_MDS_UNINSTALL_FAILED,
    MAB_SP_MAS_MDS_UNINSTALL_SUCCESS,
    MAB_SP_MAS_MDS_SUBSCR_FAILED,
    MAB_SP_MAS_MDS_SUBSCR_SUCCESS,
    MAB_SP_MAS_MDS_SND_MSG_SUCCESS,
    MAB_SP_MAS_MDS_SND_MSG_FAILED,
    MAB_SP_MAS_MDS_RCV_MSG,
    MAB_SP_MAS_MDS_RCV_EVT,
    MAB_SP_MAS_MDS_CBINFO_NULL,

    MAB_SP_OAC_MDS_INSTALL_FAILED,
    MAB_SP_OAC_MDS_INSTALL_SUCCESS,
    MAB_SP_OAC_MDS_UNINSTALL_FAILED,
    MAB_SP_OAC_MDS_UNINSTALL_SUCCESS,
    MAB_SP_OAC_MDS_SUBSCR_FAILED,
    MAB_SP_OAC_MDS_SUBSCR_SUCCESS,
    MAB_SP_OAC_MDS_SND_MSG_SUCCESS,
    MAB_SP_OAC_MDS_SND_MSG_FAILED,
    MAB_SP_OAC_MDS_RCV_MSG,
    MAB_SP_OAC_MDS_RCV_EVT,
    MAB_SP_OAC_MDS_CBINFO_NULL,

  } MAB_SVC_PRVDR_FLEX;

/******************************************************************************
 Logging offset indexes for Lock logging 
 ******************************************************************************/

typedef enum MAB_locks_flex
  {
    MAB_LK_MAC_LOCKED,
    MAB_LK_MAC_UNLOCKED,
    MAB_LK_MAC_CREATED,
    MAB_LK_MAC_DELETED,

    MAB_LK_MAS_LOCKED,
    MAB_LK_MAS_UNLOCKED,
    MAB_LK_MAS_CREATED,
    MAB_LK_MAS_DELETED,

    MAB_LK_OAC_LOCKED,
    MAB_LK_OAC_UNLOCKED,
    MAB_LK_OAC_CREATED,
    MAB_LK_OAC_DELETED

  } MAB_LOCKS_FLEX;


/******************************************************************************
 Logging offset indexes for Memory Fail logging 
 ******************************************************************************/

typedef enum mab_memfail_flex
  {
    MAB_MF_MABMSG_CREATE, 

    MAB_MF_MAC_INST_ALLOC_FAILED, 

    MAB_MF_MAS_FLTR_CREATE_FAILED,
    MAB_MF_MAS_FLTR_MIN_IDX_CREATE_FAILED, 
    MAB_MF_MAS_FLTR_MAX_IDX_CREATE_FAILED,
    MAB_MF_MAS_CSI_NODE_ALLOC_FAILED, 
    MAB_MF_MAS_TBL_ALLOC_FAILED, 
    MAB_MF_MAS_ROW_REC_ALLOC_FAILED,
    MAB_MF_MAS_MAB_FLTR_ANCHOR_NODE_ALLOC_FAILED, 
    MAB_MF_MAS_WARM_SYNC_CNTXT_ALLOC_FAILED, 
    MAB_MF_MAS_WARM_SYNC_BKT_LIST_ALLOC_FAILED,
    
    MAB_MF_OAC_FLTR_CREATE_FAILED, 
    MAB_MF_OAC_FLTR_MIN_IDX_CREATE_FAILED, 
    MAB_MF_OAC_FLTR_MAX_IDX_CREATE_FAILED,
    MAB_MF_OAC_INST_ALLOC_FAILED, 

    MAB_MF_MAB_INST_NODE_ALLOC_FAILED,
    MAB_MF_OAC_PCN_LIST_ALLOC_FAIL,
    MAB_MF_OAA_PCN_STRING_ALLOC_FAIL,
    MAB_MF_OAC_NCSOAC_PSS_TBL_LIST_ALLOC_FAIL,
    MAB_MF_OAA_WBREQ_PEND_LIST_ALLOC_FAIL,
    MAB_MF_MAB_PSS_TBL_LIST_ALLOC_FAIL,
    MAB_MF_OAA_PSS_WARMBOOT_REQ,
    MAB_MF_OAA_BUFR_HASH_LIST, 
    MAB_MF_OAA_PSS_TBL_BIND_EVT,
    MAB_MF_OAA_WBREQ_HDL_LIST_ALLOC_FAIL,

    MAB_MF_MAX
  } MAB_MEMFAIL_FLEX;

/******************************************************************************
 Logging offset indexes for API logging 
 ******************************************************************************/

typedef enum mab_api_flex
  {
    MAB_API_MAC_MIB_REQ,
    MAB_API_MAC_SVC_DESTROY,
    MAB_API_MAC_SVC_GET,
    MAB_API_MAC_SVC_SET,

    MAB_API_MAS_SVC_CREATE,
    MAB_API_MAS_SVC_DESTROY,
    MAB_API_MAS_SVC_GET,
    MAB_API_MAS_SVC_SET,

    MAB_API_OAC_SVC_CREATE,
    MAB_API_OAC_SVC_DESTROY,
    MAB_API_OAC_SVC_GET,
    MAB_API_OAC_SVC_SET,
    MAB_API_OAC_TBL_REG,
    MAB_API_OAC_TBL_UNREG,
    MAB_API_OAC_ROW_REG,
    MAB_API_OAC_ROW_UNREG
  } MAB_API_FLEX;

/******************************************************************************
 Logging offset indexes for Event logging 
 ******************************************************************************/

typedef enum mab_event_flex
  {
    MAB_EV_LM_OAC_TBL_REG_EXIST,
    MAB_EV_LM_OAC_TBL_UNREG_NONEXIST,
    MAB_EV_LM_OAC_FLTR_REG_NO_TBL,
    MAB_EV_LM_OAC_FLTR_TYPE_MM,
    MAB_EV_LM_OAC_FLTR_UNREG_NO_TBL,
    MAB_EV_LM_OAC_FLTR_UNREG_NO_FLTR,
    MAB_EV_LM_OAC_TBL_BIND_TO_PSS,
    MAB_EV_LM_OAC_TBL_UNBIND_TO_PSS,
    MAB_EV_LM_MAS_FTYPE_REG_UNSUPP,
    MAB_EV_LM_MAS_FTYPE_REG_MM,
    MAB_EV_LM_MAS_FSIZE_REG_MM,
    MAB_EV_LM_MAS_FLTR_REG_EXIST,
    MAB_EV_LM_OVRLAP_FLTR,
    MAB_EV_LM_MAS_FLTR_REG_INV_SA,
    MAB_EV_LM_MAS_FLTR_REG_SS_MM,
    MAB_EV_LM_MAS_FLTR_UNREG_NO_FLTR,
    MAB_EV_LM_MAS_FLTR_UNREG_SS_MM,
    MAB_EV_LM_MAS_FLTR_MRRSP_NO_FLTR
    
  } MAB_EVENT_FLEX;

/*****************************************************************************
 Logging Errors                              
******************************************************************************/
typedef enum MAB_error_flex
{
    MAB_MAC_ERR_INVALID_MIB_REQ_OP, 
    MAB_MAC_ERR_MDS_CB_INVALID_OP, 
    MAB_MAC_ERR_SPLR_REG_FAILED,
    MAB_MAC_ERR_SPLR_DEREG_FAILED,
    MAB_MAC_ERR_IPC_CREATE_FAILED,
    MAB_MAC_ERR_IPC_ATTACH_FAILED,
    MAB_MAC_ERR_TASK_CREATE_FAILED,
    MAB_MAC_ERR_TASK_START_FAILED,
    MAB_MAC_ERR_CREATE_FAILED, 
    MAB_MAC_ERR_SPIR_LOOKUP_CREATE_FAILED,
    MAB_MAC_ERR_DESTROY_FAILED,
    MAB_MAC_ERR_SPIR_RMV_INST_FAILED,
    MAB_MAC_ERR_INST_LIST_ADD_FAILED,
    MAB_MAC_ERR_NO_LM_CALLBACK, 
    MAB_MAC_ERR_CB_ALLOC_FAILED_ENVID, 
    MAB_MAC_ERR_PWE_QUERY_FAILED, 
    MAB_MAC_ERR_CREATED_ON_NON_ADEST,
    MAB_MAC_ERR_MDS_INSTALL_FAILED, 
    MAB_MAC_ERR_MDS_SUBSCRB_FAILED, 
    MAB_MAC_ERR_MDS_UNINSTALL_FAILED, 
    MAB_MAC_ERR_CB_NULL,
    MAB_MAC_ERR_SPIR_REL_INST_FAILED, 
    MAB_MAC_ERR_MDS_TO_MBX_SND_FAILED, 
    
    MAB_MAS_ERR_IPC_CREATE_FAILED, 
    MAB_MAS_ERR_IPC_ATTACH_FAILED, 
    MAB_MAS_ERR_SIG_INSTALL_FAILED, 
    MAB_MAS_ERR_TASK_CREATE_FAILED, 
    MAB_MAS_ERR_TASK_START_FAILED, 
    MAB_MAS_ERR_VDEST_CREATE_FAILED, 
    MAB_MAS_ERR_LM_CREATE_FAILED, 
    MAB_MAS_ERR_LM_DESTROY_FAILED, 
    MAB_MAS_ERR_DEF_ENV_INIT_FAILED, 
    MAB_MAS_ERR_MDS_PWE_CREATE_FAILED, 
    MAB_MAS_ERR_VDEST_ROLE_CHANGE_FAILED, 
    MAB_MAS_ERR_MDS_PWE_INSTALL_FAILED, 
    MAB_MAS_ERR_MDS_SUBSCRIBE_FAILED, 
    MAB_MAS_ERR_MDS_CB_INVALID_OP, 
    MAB_MAS_ERR_FLTR_SA_INVALID_TBL, 
    MAB_MAS_ERR_SNT_NO_TBL_RSP_FAILED,
    MAB_MAS_ERR_SNT_NO_TBL_RSP, 
    MAB_MAS_ERR_DEF_FLTR_NOT_REGISTERED, 
    MAB_MAS_ERR_MAC_SND_FAILED, 
    MAB_MAS_ERR_OAA_SND_FAILED, 
    MAB_MAS_ERR_NO_NI_FRWD_TO_MAC, 
    MAB_MAS_ERR_AMF_ENVID_ILLEGAL, 
    MAB_MAS_ERR_AMF_DISPATCH_FAILED, 
    MAB_MAS_ERR_DO_EVTS_FAILED, 
    MAB_MAS_ERR_AMF_ATTRIBS_INIT_FAILED, 
    MAB_MAS_ERR_AMF_INITIALIZE_FAILED,
    MAB_MAS_ERR_MDS_PWE_QUERY_FAILED, 
    MAB_MAS_ERR_MDS_VDEST_ROLE_CHG_FAILED,
    MAB_MAS_ERR_MDS_UNINSTALL_FAILED, 
    MAB_MAS_ERR_MDS_PWE_DESTROY_FAILED,
    MAB_MAS_ERR_MASTBL_DESTROY_FAILED, 
    MAB_MAS_ERR_CSI_DELINK_FAILED,
    MAB_MAS_ERR_AMF_CSI_REMOVE_ALL_FAILED, 
    MAB_MAS_ERR_VDEST_DESTROY_FAILED, 
    MAB_MAS_ERR_APP_AMF_FINALIZE_FAILED, 
    MAB_MAS_ERR_CSI_ADD_ONE_FAILED,
    MAB_MAS_ERR_AMF_CSI_FLAGS_ILLEGAL,
    MAB_MAS_ERR_AMF_CSI_ATT_COUNT_INVD,
    MAB_MAS_ERR_AMF_CSI_ATTRIBS_NULL, 
    MAB_MAS_ERR_AMF_CSI_ATTS_NAME_OR_ATTRIB_VAL_NULL,
    MAB_MAS_ERR_AMF_CSI_ATTRIBS_NAME_INVALID,
    MAB_MAS_ERR_AMF_CSI_SSCANF_FAILED,
    MAB_MAS_ERR_AMF_CSI_DECODED_ENV_ID_OUTOF_REACH,
    MAB_MAS_ERR_AMF_FINALIZE_FAILED, 
    MAB_MAS_ERR_MOVEROW_MAC_SND_FAILED,
    MAB_MAS_ERR_MOVEROW_OAC_SND_FAILED,
    MAB_MAS_ERR_INFORM,
    MAB_MAS_ERR_AMF_TIMER_FAILED,
    MAB_MAS_ERR_SIGUSR2_INSTALL_FAILED,
    MAB_MAS_ERR_MDS_TO_MBX_SND_FAILED,
    MAB_MAS_ERR_MBCSV_INIT_FAILED, 
    MAB_MAS_ERR_MBCSV_SEL_OBJ_GET_FAILED,
    MAB_MAS_ERR_MBCSV_DISPATCH_FAILED, 
    MAB_MAS_ERR_MBCSV_CKPT_CLOSE_FAILED,
    MAB_MAS_ERR_MBCSV_CKPT_OPEN_FAILED, 
    MAB_MAS_ERR_MBCSV_CKPT_CHG_ROLE_FAILED, 
    MAB_MAS_ERR_MBCSV_ENC_UNSUP_MSG_TYPE, 
    MAB_MAS_ERR_MBCSV_DEC_UNSUP_MSG_TYPE, 
    MAB_MAS_ERR_MBCSV_CB_ERR_IND, 
    MAB_MAS_ERR_COLD_SYNC_DEC_BKT_NON_NULL, 
    MAB_MAS_ERR_COLD_SYNC_ENC_BKT_FAILED, 
    MAB_MAS_ERR_COLD_SYNC_DEC_BKT_FAILED, 
    MAB_MAS_ERR_MBCSV_OP_NOT_SUPPORTED, 
    MAB_MAS_ERR_AMF_SBY_TO_ACT_FAILED_COLD_SYNC, 
    MAB_MAS_ERR_AMF_SBY_TO_ACT_FAILED_WARM_SYNC, 
    MAB_MAS_ERR_MBCSV_API_SND_USR_ASYNC_FAILED, 
    MAB_MAS_ERR_MBCSV_ENC_FAILED, 
    MAB_MAS_ERR_MBCSV_DEC_FAILED, 
    MAB_MAS_ERR_MBCSV_WARM_SYNC_BKT_CNT_ZERO, 
    MAB_MAS_ERR_MBCSV_DATA_RSP_ENCODE_FAILED_FOR_BKT,
    MAB_MAS_ERR_MBCSV_API_DATA_REQ_FAILED,
    MAB_MAS_ERR_MBCSV_DATA_REQ_DEC_BKTCNT_ZERO, 
    MAB_MAS_ERR_PREPARE_WILL_FAILED,
    MAB_MAS_ERR_MBCSV_FINALIZE_FAILED, 
    MAB_MAS_ERR_MBCSV_CB_NULL_ARG,
    MAB_MAS_ERR_MBCSV_CB_INVALID_HDL, 
    MAB_MAS_ERR_AMF_INVALID_ROLE, 
    MAB_MAS_ERR_AMF_INCONSISTENT_CSI,
    MAB_MAS_ERR_AMF_STATE_CHG_FAILED,
    MAB_MAS_ERR_RDA_INIT_ROLE_GET_FAILED,
    MAB_MAS_ERR_GET_ROLE_FAILED,

    MAB_OAC_ERR_ENV_ID_MM,
    MAB_OAC_ERR_RSP_UNKNWN_SVC_ID, 
    MAB_OAC_ERR_REQ_UNKNWN_SVC_ID, 
    MAB_OAC_ERR_MDS_CB_INVALID_OP,
    MAB_OAC_ERR_SPLR_REG_FAILED,
    MAB_OAC_ERR_SPLR_DEREG_FAILED,
    MAB_OAC_ERR_IPC_CREATE_FAILED,
    MAB_OAC_ERR_IPC_ATTACH_FAILED,
    MAB_OAC_ERR_TASK_CREATE_FAILED,
    MAB_OAC_ERR_TASK_START_FAILED,
    MAB_OAC_ERR_CREATE_FAILED,
    MAB_OAC_ERR_DESTROY_FAILED,
    MAB_OAC_ERR_SPIR_RMV_INST_FAILED,
    MAB_OAC_ERR_INST_LIST_ADD_FAILED,
    MAB_OAC_ERR_NO_LM_CALLBACK, 
    MAB_OAC_ERR_CB_ALLOC_FAILED_ENVID, 
    MAB_OAC_ERR_SPIR_LOOKUP_CREATE_FAILED, 
    MAB_OAC_ERR_PWE_QUERY_FAILED, 
    MAB_OAC_ERR_MDS_INSTALL_FAILED, 
    MAB_OAC_ERR_MDS_SUBSCRB_FAILED, 
    MAB_OAC_ERR_MDS_OAA_SUBSCRB_FAILED,
    MAB_OAC_ERR_MDS_UNINSTALL_FAILED, 
    MAB_OAC_ERR_CB_NULL, 
    MAB_OAC_ERR_SPIR_REL_INST_FAILED, 
    MAB_OAC_ERR_MDS_TO_MBX_SND_FAILED,

    /* RDA interface related errors */
    MAB_ERR_RDA_INVALID_OP_LOC,
    MAB_ERR_RDA_LIB_INIT_FAILED,
    MAB_ERR_RDA_API_GET_ROLE_FAILED,
    MAB_ERR_RDA_INVALID_ROLE,
    MAB_ERR_RDA_LIB_FIN_FAILED,
    
    MAB_ERROR_FLEX_MAX
}MAB_ERROR_FLEX;


typedef enum mab_oaa_pcn_info_1_flex 
{
   MAB_OAA_PCN_INFO_TBL_IN_WARMBOOT_REQ_NOT_PERSISTENT,
   MAB_OAA_PCN_INFO_WARMBOOT_REQ_TBL_NOT_FND_IN_PCN_LIST,
   MAB_OAA_PCN_INFO_TBL_MADE_NON_PERSISTENT,
   MAB_OAA_PCN_INFO_PSS_NOT_PRESENT_DURING_TBL_REG,
   MAB_OAA_PCN_INFO_UNBIND_REQ_TO_PSS_MDS_SND_FAIL,
   MAB_OAA_PCN_INFO_UNBIND_REQ_TO_PSS_MDS_SND_SUCCESS,
   MAB_OAA_PCN_INFO_TBL_FND_IN_PCN_LIST_DURING_UNBIND_OP,
   MAB_OAA_PCN_INFO_TBL_NOT_FND_IN_PCN_LIST_DURING_UNBIND_OP
}MAB_OAA_PCN_INFO_I_FLEX;
  
typedef enum mab_oaa_pcn_info_2_flex 
{
   MAB_OAA_PCN_INFO_PCN_FND_IN_PCN_LIST_OAC_FINDADD_PCN_IN_LIST_FUNC,
   MAB_OAA_PCN_INFO_BIND_REQ_TO_PSS_MDS_SND_FAIL,
   MAB_OAA_PCN_INFO_BIND_REQ_TO_PSS_MDS_SND_SUCCESS,
   MAB_OAA_PCN_INFO_WARMBOOT_REQ_FOR_NON_PERSISTENT_TABLE_RCVD,
   MAB_OAA_PCN_INFO_WARMBOOT_REQ_FOR_NON_BOUND_TABLE_RCVD
}MAB_OAA_PCN_INFO_II_FLEX;
  
typedef enum mab_oaa_warmbootreq_info_1_flex 
{
   MAB_OAA_WARMREQ_INFO_I_PSS_MAS_STATUS
}MAB_OAA_WARMBOOTREQ_INFO_I_FLEX;
  
typedef enum mab_oaa_warmbootreq_info_2_flex 
{
   MAB_OAA_WARMREQ_INFO_II_RCVD_REQ,
   MAB_OAA_WARMREQ_INFO_II_REQ_MDS_EVT_TO_PSS_COMPOSED
}MAB_OAA_WARMBOOTREQ_INFO_II_FLEX;
  
typedef enum mab_oaa_warmbootreq_info_3_flex 
{
   MAB_OAA_WARMREQ_INFO_III_REQ_MDS_EVT_TO_PSS_COMPOSED
}MAB_OAA_WARMBOOTREQ_INFO_III_FLEX;
  

/******************************************************************************/

/******************************************************************************
 Logging offset indexes for canned constant strings for the ASCII SPEC
 ******************************************************************************/
typedef enum mab_flex_sets
{
    MAB_FC_HDLN,
    MAB_FC_SVC_PRVDR_FLEX,
    MAB_FC_LOCKS,
    MAB_FC_MEMFAIL,
    MAB_FC_API,
    MAB_FC_EVT, 
    MAB_FC_TBL_DET, 
    MAB_FC_FLTR_DET, 
    MAB_FC_ERROR,
    MAB_FC_OAA_PCN_INFO_I,
    MAB_FC_OAA_PCN_INFO_II,
    MAB_FC_OAA_WARMBOOTREQ_INFO_I,
    MAB_FC_OAA_WARMBOOTREQ_INFO_II,
    MAB_FC_OAA_WARMBOOTREQ_INFO_III
} MAB_FLEX_SETS;


typedef enum mab_log_ids
  {
    MAB_LID_HDLN, /* 0 */
    MAB_LID_SVC_PRVDR_FLEX,
    MAB_LID_LOCKS,
    MAB_LID_MEMFAIL,
    MAB_LID_API, /* 4 */ 
    MAB_LID_EVT,
    MAB_LID_TBL_DET,
    MAB_LID_FLTR_DET, 
    MAB_LID_SVC_PRVDR_EVT,
    MAB_LID_SVC_PRVDR_MSG,  /* 9 */ 
    MAB_LID_FLTR_RANGE, 
    MAB_LID_FLTR_RANGE_INDEX, 
    MAB_LID_FLTR_ANY, 
    MAB_LID_FLTR_SA, 
    MAB_LID_FLTR_DEF,  /* 14 */ 
    MAB_LID_NO_CB, 
    MAB_LID_ERR_II, 
    MAB_LID_ERR_I, 
    MAB_LID_CSI,
    MAB_LID_ST_CHG,  /* 19 */
    MAB_LID_MEM,
    MAB_LID_ERROR, 
    MAB_LID_HDLN_I,
    MAB_LID_HDLN_II,
    MAB_LID_OAA_BIND_EVT,
    MAB_LID_OAA_UNBIND_EVT,
    MAB_LID_FLTR_EXACT,
    MAB_LID_FLTR_EXACT_INDEX,
    MAB_LID_OAA_PCN_INFO_I,
    MAB_LID_OAA_PCN_INFO_II,
    MAB_LID_OAA_WARMBOOTREQ_INFO_I,
    MAB_LID_OAA_WARMBOOTREQ_INFO_II,
    MAB_LID_OAA_WARMBOOTREQ_INFO_III,
    MAB_LID_ANC 
  } MAB_LOG_IDS;


/*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

                          MASV Logging Control

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*/

EXTERN_C uns32
mab_log_str_lib_req(NCS_LIB_REQ_INFO *req_info);

/* DTSv versioning support */
#define MASV_LOG_VERSION 4 

#endif /* MAB_LOG_CONST_H */
