#      -*- OpenSAF  -*-
#
# Copyright Ericsson AB 2017 - All Rights Reserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
# under the GNU Lesser General Public License Version 2.1, February 1999.
# The complete license can be accessed from the following location:
# http://opensource.org/licenses/lgpl-license.php
# See the Copying file included with the OpenSAF distribution for full
# licensing terms.
#

all:
	$(MAKE) -C ../../.. \
		lib/libSaAmf.la \
		lib/libSaCkpt.la \
		lib/libSaClm.la \
		lib/libSaEvt.la \
		lib/libSaImmOi.la \
		lib/libSaImmOm.la \
		lib/libSaLck.la \
		lib/libSaLog.la \
		lib/libSaMsg.la \
		lib/libSaNtf.la \
		lib/libSaPlm.la \
		lib/libSaSmf.la \
		lib/libais.la
