#      -*- OpenSAF  -*-
#
# (C) Copyright 2008 The OpenSAF Foundation
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
# under the GNU Lesser General Public License Version 2.1, February 1999.
# The complete license can be accessed from the following location:
# http://opensource.org/licenses/lgpl-license.php
# See the Copying file included with the OpenSAF distribution for full
# licensing terms.
#

#
# opensaf/tests/Makefile.common
#
# included by opensaf/tests/Makefile and Makefiles for each service
#

OS := $(shell uname -s)
curdir := $(shell pwd)

#
# CC_EXEC_PREFIX
# If not set in the environment, defaults to the empty string (no prefix).
#
CC_EXEC_PREFIX ?=

CAT=	/bin/cat
CHMOD=	/usr/bin/chmod
CP=	/bin/cp
DIFF=	/usr/bin/diff
ECHO=	echo
GZIP=	/usr/bin/gzip
LD=	/usr/bin/$(CC_EXEC_PREFIX)ld
LN=	/bin/ln
MAKE=	/usr/bin/gmake
MKDIR=	/bin/mkdir
RM=	/bin/rm -f
RMDIR=	/bin/rmdir
TAR=	/usr/bin/tar
GREP=	/bin/grep

ifeq "$(OS)" "SunOS"
LD=	/usr/ccs/bin/ld
MAKE=	/usr/sfw/bin/gmake
MKDIR=	/usr/bin/mkdir
RMDIR=	/usr/bin/rmdir
endif

#
# OPENSAF_ROOT is the base directory of the opensaf source,
# which contains source files for both the product and tests.
# The build of tests depends on header files from OPENSAF_ROOT.
# If not already set, defaults to the value below.
#
OPENSAF_ROOT ?= /home/opensaf

#
# TARGET_ARCH
# If not set in the environment, defaults to the value below.
#
TARGET_ARCH ?= 

#
# PLATFORM
# Possible values are linux | linux-64 | solaris
# If not set in the environment, defaults to linux.
#
PLATFORM ?= linux

#
# TET_HOME is the base directory of the built tetware open source.
# If not set in the environment, defaults to the value below.
#
TET_HOME ?= /usr/local/tet

COMPILER := $(CC_EXEC_PREFIX)gcc

NCS_DEFINES := -DNCS_SAF=1
#NCS_DEFINES += -DNCS_MMGR_DEBUG=1 -DNDEBUG=1 
CPPFLAGS := $(NCS_DEFINES) -DENABLE_LEAP_DBG=0
# need following to get the standard-conforming ctime_r() function
ifeq "$(OS)" "SunOS"
CPPFLAGS += -D_POSIX_PTHREAD_SEMANTICS
endif
CPPFLAGS += -I./inc
CPPFLAGS += -I../common/inc
CPPFLAGS += -I/usr/include/opensaf
CPPFLAGS += -I$(TET_HOME)/inc/tet3

CFLAGS = -c -g -Wall

#
# LIB_BASEDIR is the location of the OpenSAF libraries to link with.
# If not set in the environment, defaults to the value below.
#
LIB_BASEDIR ?= /usr/lib/

LIBSUBDIR := opensaf

LIBDIR := $(LIB_BASEDIR)/$(LIBSUBDIR)

LDLIBS := -lncs_core \
	$(TET_HOME)/lib/tet3/tcm.o \
	$(TET_HOME)/lib/tet3/libapi.a \
	$(TET_HOME)/lib/tet3/libtcm_s.a \
	-lpthread -ldl -lm -lc -lrt

