/*      -*- OpenSAF  -*-
 *
 * (C) Copyright 2008 The OpenSAF Foundation
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
 * under the GNU Lesser General Public License Version 2.1, February 1999.
 * The complete license can be accessed from the following location:
 * http://opensource.org/licenses/lgpl-license.php
 * See the Copying file included with the OpenSAF distribution for full
 * licensing terms.
 *
 * Author(s): Emerson Network Power
 *
 */

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else    /* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif    /* __STDC__ */
#endif    /* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 *     if ( condition_holds )
 *        yyless( 5 );
 *    else
 *        do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
    do \
        { \
        /* Undo effects of setting up yytext. */ \
        *yy_cp = yy_hold_char; \
        YY_RESTORE_YY_MORE_OFFSET \
        yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up yytext again */ \
        } \
    while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
    {
    FILE *yy_input_file;

    char *yy_ch_buf;        /* input buffer */
    char *yy_buf_pos;        /* current position in input buffer */

    /* Size of input buffer in bytes, not including room for EOB
     * characters.
     */
    yy_size_t yy_buf_size;

    /* Number of characters read into yy_ch_buf, not including EOB
     * characters.
     */
    int yy_n_chars;

    /* Whether we "own" the buffer - i.e., we know we created it,
     * and can realloc() it to grow it, and should free() it to
     * delete it.
     */
    int yy_is_our_buffer;

    /* Whether this is an "interactive" input source; if so, and
     * if we're using stdio for input, then we want to use getc()
     * instead of fread(), to make sure we stop fetching input after
     * each newline.
     */
    int yy_is_interactive;

    /* Whether we're considered to be at the beginning of a line.
     * If so, '^' rules will be active on the next match, otherwise
     * not.
     */
    int yy_at_bol;

    /* Whether to try to fill the input buffer when we reach the
     * end of it.
     */
    int yy_fill_buffer;

    int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
     * then we mark the buffer as YY_EOF_PENDING, to indicate that we
     * shouldn't try reading from the input source any more.  We might
     * still have a bunch of tokens to match, though, because of
     * possible backing-up.
     *
     * When we actually see the EOF, we change the status to "new"
     * (via yyrestart()), so that the user can continue scanning by
     * just pointing yyin at a new input file.
     */
#define YY_BUFFER_EOF_PENDING 2
    };

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;        /* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;        /* whether we need to initialize */
static int yy_start = 0;    /* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
    { \
    if ( ! yy_current_buffer ) \
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
    yy_current_buffer->yy_is_interactive = is_interactive; \
    }

#define yy_set_bol(at_bol) \
    { \
    if ( ! yy_current_buffer ) \
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
    yy_current_buffer->yy_at_bol = at_bol; \
    }

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
    yytext_ptr = yy_bp; \
    yyleng = (int) (yy_cp - yy_bp); \
    yy_hold_char = *yy_cp; \
    *yy_cp = '\0'; \
    yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 39
#define YY_END_OF_BUFFER 40
static yyconst short int yy_accept[205] =
    {   0,
        0,    0,   40,   39,   25,   27,   26,   39,   39,   39,
       17,   17,   16,   33,   34,   39,   19,   19,   30,   31,
       28,   32,   29,   25,    0,    0,   38,   22,    0,    0,
        0,    0,    0,   36,    0,   21,    0,    0,    0,   17,
       17,   19,    0,   16,    0,   35,    0,    0,    0,    0,
        0,   37,    0,   23,   19,   38,    0,    0,    0,    0,
        0,    0,   38,    0,    0,   38,    0,    0,   38,    0,
        0,   38,    0,    0,    0,    0,    0,    0,    0,   16,
        0,   19,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   16,    0,    0,

        0,   20,    0,    0,   19,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   19,    0,    0,    0,    0,    0,
        0,    0,    0,   19,    0,    0,   24,   24,   24,   24,
       10,    0,   19,    0,    0,   10,   19,   19,   19,   19,
       19,   19,    0,   10,   19,   19,   19,   19,   19,   19,
       19,    0,   19,   19,   19,    0,   19,   19,   19,   19,
       19,    0,   19,   19,    9,    7,    8,    6,   19,   19,
       19,   19,   19,    0,   19,    0,   19,   19,   19,    0,
       19,   19,   19,    0,    5,   14,    4,   13,   19,   19,
       12,   11,   15,   19,   19,   19,    2,   19,   19,   19,

       18,    1,    3,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    4,
        1,    1,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    2,    2,    2,    8,    2,    2,    9,
       10,   11,    1,    2,   12,   13,   14,   15,   15,   15,
       15,   16,   15,   17,   15,   15,   15,    2,    2,   18,
        2,   19,    2,   20,   21,   22,   23,   24,   25,   26,
       26,   26,   27,   26,   28,   29,   30,   31,   32,   33,
       26,   34,   35,   36,   37,   38,   39,   26,   40,   26,
       41,    1,   42,    2,   43,    2,   44,   44,   44,   44,

       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   45,   44,   44,
       44,   44,   46,   47,   48,    2,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[49] =
    {   0,
        1,    2,    2,    3,    1,    2,    4,    5,    6,    7,
        8,    9,    2,    2,   10,   10,   10,    6,   11,   12,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
        6,   14,    9,   10,   10,    6,    2,   15
    } ;

static yyconst short int yy_base[226] =
    {   0,
        0,    0,  606, 1376,   46, 1376, 1376,   52,  100,    0,
        0,  138,   50,  183, 1376,  231,  269,  582, 1376, 1376,
     1376, 1376, 1376,   48,  554,  314,   51, 1376,  362,  410,
      458,  506,  549, 1376,    0, 1376,    0,   68,  554,    0,
      592,    0,   62,   71,  547, 1376,    0,    0,   51,  152,
      546, 1376,    0, 1376,  514, 1376,  281,  536,  526,  502,
      495,  637,  532,    0,  685,  522,    0,  733,  498,    0,
      781,  491,    0,  155,  158,  285,    0,  829,  163,   74,
      877,  515,  527,  285,  514,  288,  486,  298,  478,  302,
      334,  369,    0,    0,  925,  266,  374,  501,    0,    0,

      390, 1376,  387,    0,  484,  337,  408,    0,  973, 1021,
     1069,  385,  496,  410,  478,  422,   69,  493,  492,  491,
      488,  320,  427,  454,  342,  432, 1376,    0,    0,    0,
      353,  483,  442,  470,  147,  467,   48,  462,  473,  456,
      468,  453,  504, 1376,  447,  440,  119,  273,  436,  429,
      432,  514,  426,  427,   79,  348,  429,  418,  419,  399,
      409,  475,  272,  390, 1376, 1376, 1376, 1376,  389,  338,
      370,  353,  351,  519,  362,  401,  330,  321,  326,  324,
      296,  280,  283,  384, 1376, 1376, 1376, 1376,  260,  168,
     1376, 1376,    0,  143,  132,  116,    0,   75,   44,   10,

        0,    0,    0, 1376, 1117,  315, 1125, 1128, 1141, 1155,
     1168, 1183, 1198, 1213, 1228, 1243, 1258, 1272, 1284, 1296,
     1309, 1324, 1339, 1354, 1362
    } ;

static yyconst short int yy_def[226] =
    {   0,
      204,    1,  204,  204,  204,  204,  204,  205,  204,  206,
      207,  208,  207,  204,  204,  204,  208,   17,  204,  204,
      204,  204,  204,  204,  209,  205,  210,  204,  211,  212,
      213,  214,  215,  204,    9,  204,    9,  215,  204,  207,
       17,   17,  204,   13,  216,  204,   14,   14,  216,  216,
      217,  204,   16,  204,   17,  204,  210,  218,  219,  220,
      221,  211,  218,   26,  212,  219,   26,  213,  220,   26,
      214,  221,   26,  215,  215,  215,  222,  204,  204,   13,
      204,   17,  218,  210,  219,  210,  220,  210,  221,  210,
      215,  215,  223,  224,  204,  204,  204,   80,   81,   81,

      216,  204,   81,   81,   17,  215,  215,  225,  225,  204,
      204,  204,  204,   81,   17,  215,  215,  225,  109,  110,
      111,  204,  204,   17,  215,  215,  204,  225,  109,  110,
      204,  204,   17,  215,  215,  204,   17,   17,   17,   17,
       17,   17,  215,  204,   17,   17,   17,   17,   17,   17,
       17,  215,   17,   17,   17,  204,   17,   17,   17,   17,
       17,  215,   17,   17,  204,  204,  204,  204,   17,   17,
       17,   17,   17,  215,   17,  204,   17,   17,   17,  204,
       17,   17,   17,  215,  204,  204,  204,  204,   17,   17,
      204,  204,   17,   17,   17,   17,   17,   17,   17,   17,

       17,   17,   17,    0,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204
    } ;

static yyconst short int yy_nxt[1425] =
    {   0,
        4,    4,    5,    6,    7,    5,    8,    9,   10,    4,
       11,   12,    4,    4,   13,   13,   13,   14,   15,   16,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       18,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       19,   20,   12,   11,   11,   21,   22,   23,   24,  203,
       24,   24,   25,   24,   46,   27,   25,   28,   28,   58,
       29,   25,   43,   81,   44,   44,   44,  202,   59,   30,
       25,   34,   34,   74,  145,   36,   79,   79,   79,  146,
       75,  106,   76,   76,   76,   80,   80,   80,   98,   98,
       98,   60,   31,   25,  165,  166,   61,   32,  201,   25,

       33,   33,   33,   34,   33,   35,   33,   36,   33,   33,
       33,   37,   33,   33,   38,   38,   38,   33,   33,   33,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       33,   33,   37,   37,   37,   33,   33,   33,   40,   41,
       34,  200,   40,   40,   40,   46,  155,   50,   34,  125,
       74,   34,   36,  156,   49,  199,   50,   50,   50,   38,
       38,   38,   91,   91,   91,   96,  198,   97,   97,   97,
       41,   40,   40,   45,   45,   45,   46,   45,   47,   45,
       45,   45,   45,   45,   48,   49,   45,   50,   50,   50,

       45,  197,   45,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   45,   45,   48,   48,   48,   45,   45,
       45,   51,   51,   51,   52,   51,   51,   51,   51,   51,
       51,   51,   53,   51,   53,   53,   53,   53,   51,   51,
       54,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   51,   51,   53,   53,   53,   51,   51,   51,  204,
      112,  112,  112,  204,  204,  204,  196,   28,   34,   58,
       74,   28,   36,   58,   28,  157,   58,   75,   59,   92,

       92,   92,   59,  195,   28,   59,   58,  158,   28,  175,
       58,  194,  204,  204,   25,   59,  176,   27,   25,   59,
       28,   60,   29,   25,   39,   60,   61,   39,   60,  193,
       61,   30,   25,   61,  131,  131,  131,   34,   60,  192,
       34,  191,   60,   61,  190,   34,  106,   61,  107,  107,
      107,  116,  116,  116,   31,   25,  134,  134,  134,   32,
      189,   25,   25,  167,  168,   63,   25,  136,  136,  136,
       25,   64,   34,  183,   74,  179,   36,  185,  186,   25,
       25,   75,  180,   92,   92,   92,   96,   34,  113,  113,
      113,  182,  114,   46,  181,  101,   75,  122,  103,  123,

      123,  123,   25,   25,  101,  101,  101,   25,  102,   25,
       25,   34,  178,   66,   25,  114,  187,  188,   25,   25,
      106,  103,  117,  117,  117,   34,  177,   25,   67,  103,
       45,   45,  173,  172,  125,   34,  126,  126,  126,  122,
      171,  132,  132,  132,  125,  170,  135,  135,  135,  169,
       25,   25,  103,   45,   45,   25,  164,   25,   25,  163,
      161,   69,   25,  160,  137,  159,   25,   25,  138,  154,
      153,  139,  140,   34,  141,   25,   25,   36,   34,  151,
      142,  144,  144,  144,  143,  143,  143,   75,  150,  174,
      174,  174,  149,  148,  147,  122,  133,  130,   25,   70,

      129,  128,  127,   25,  124,   25,   25,   34,   96,   72,
       25,   36,  115,  204,   25,   25,   75,   34,  152,  152,
      152,   36,   34,   25,   25,   90,   75,   88,  162,  162,
      162,   75,   86,  184,  184,  184,   84,  105,   90,   88,
       86,   84,   90,   88,   86,   84,   25,   25,   82,   52,
       46,   25,   34,   73,   77,   77,   77,   56,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   78,   78,
       78,   77,   77,   77,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   77,   77,   77,   78,   78,   77,

       77,   77,   40,   41,   55,  204,   40,   40,   40,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,   41,   40,   40,   25,  204,  204,
       63,   25,  204,  204,  204,   25,   64,  204,  204,  204,
      204,  204,  204,  204,   25,   25,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,   25,   25,  204,
      204,  204,   25,  204,   25,   25,  204,  204,   66,   25,
      204,  204,  204,   25,   25,  204,  204,  204,  204,  204,

      204,  204,   25,   67,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,   25,   25,  204,  204,  204,
       25,  204,   25,   25,  204,  204,   69,   25,  204,  204,
      204,   25,   25,  204,  204,  204,  204,  204,  204,  204,
       25,   25,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,   25,   70,  204,  204,  204,   25,  204,
       25,   25,  204,  204,   72,   25,  204,  204,  204,   25,
       25,  204,  204,  204,  204,  204,  204,  204,   25,   25,

      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,   25,   25,  204,  204,  204,   25,  204,   73,   94,
       94,   94,  204,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   95,   95,   95,   94,   94,   94,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   94,
       94,   94,   95,   95,   94,   94,   94,   45,   45,   45,
       46,   45,   99,   45,   45,   45,   45,   45,  100,   45,
       45,  101,  101,  101,   45,  102,   45,  103,  103,  103,

      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,   45,   45,  100,
      104,  104,   45,   45,   45,  110,  110,  110,  204,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  111,
      111,  111,  110,  110,  110,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  110,  110,  110,  111,  111,
      110,  110,  110,  108,  108,  108,  204,  108,  108,  108,
      108,  108,  108,  204,  108,  108,  108,  204,  204,  204,
      108,  108,  108,  204,  204,  204,  204,  204,  204,  204,

      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  108,  108,  108,  204,  204,  108,  108,
      108,  109,  109,  109,  204,  109,  109,  109,  109,  109,
      109,  119,  109,  109,  109,  119,  119,  119,  109,  109,
      109,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  109,  109,  109,  119,  119,  109,  109,  109,  110,
      110,  110,  204,  110,  110,  110,  110,  110,  110,  120,
      110,  110,  110,  121,  121,  121,  110,  110,  110,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,

      121,  121,  121,  121,  121,  121,  121,  121,  121,  110,
      110,  110,  121,  121,  110,  110,  110,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   40,   40,   40,   42,   42,   42,  204,  204,
       42,   25,   25,   25,  204,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   57,   57,   57,   57,
       57,  204,   57,   57,   57,  204,   57,   57,   62,   62,
       62,  204,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   65,   65,   65,  204,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   68,   68,

       68,  204,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   71,   71,   71,  204,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   33,   33,
       33,   33,  204,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,  204,   45,   45,   45,   45,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,  204,
       51,   51,   51,   83,   83,  204,   83,  204,   83,   83,
       83,   83,  204,   83,   83,   85,   85,  204,   85,  204,
      204,   85,   85,   85,   85,   85,   85,   87,   87,  204,

       87,  204,  204,   87,   87,   87,  204,   87,   87,   87,
       89,   89,  204,   89,  204,  204,   89,   89,   89,  204,
       89,   89,  204,   89,   93,   93,  204,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,  108,
      108,  204,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  109,  109,  204,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  118,
      204,  118,  204,  204,  118,    3,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,

      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204
    } ;

static yyconst short int yy_chk[1425] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,  200,
       24,    5,    8,   24,   49,    8,    8,   27,    8,   27,
        8,    8,   13,   49,   13,   13,   13,  199,   27,    8,
        8,   38,  117,   38,  137,   38,   43,   43,   43,  137,
       38,  117,   38,   38,   38,   44,   44,   44,   80,   80,
       80,   27,    8,    8,  155,  155,   27,    8,  198,    8,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,   12,   12,
      135,  196,   12,   12,   12,   50,  147,   50,   74,  135,
       74,   75,   74,  147,   50,  195,   50,   50,   50,   74,
       74,   74,   75,   75,   75,   79,  194,   79,   79,   79,
       12,   12,   12,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,

       14,  190,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   17,
       96,   96,   96,   17,   17,   17,  189,   57,   76,   57,
       76,   84,   76,   84,   86,  148,   86,   76,   57,   76,

       76,   76,   84,  183,   88,   86,   88,  148,   90,  163,
       90,  182,   17,   17,   26,   88,  163,   26,   26,   90,
       26,   57,   26,   26,  206,   84,   57,  206,   86,  181,
       84,   26,   26,   86,  122,  122,  122,   91,   88,  180,
      106,  179,   90,   88,  178,  125,   91,   90,   91,   91,
       91,  106,  106,  106,   26,   26,  125,  125,  125,   26,
      177,   26,   29,  156,  156,   29,   29,  131,  131,  131,
       29,   29,   92,  173,   92,  170,   92,  175,  175,   29,
       29,   92,  170,   92,   92,   92,   97,  184,   97,   97,
       97,  172,  103,  101,  171,  101,  184,  112,  103,  112,

      112,  112,   29,   29,  101,  101,  101,   29,  101,   29,
       30,  107,  169,   30,   30,  114,  176,  176,   30,   30,
      107,  114,  107,  107,  107,  116,  164,   30,   30,  103,
      103,  103,  161,  160,  116,  126,  116,  116,  116,  123,
      159,  123,  123,  123,  126,  158,  126,  126,  126,  157,
       30,   30,  114,  114,  114,   30,  154,   30,   31,  153,
      151,   31,   31,  150,  133,  149,   31,   31,  133,  146,
      145,  133,  133,  134,  133,   31,   31,  134,  162,  142,
      133,  136,  136,  136,  134,  134,  134,  162,  141,  162,
      162,  162,  140,  139,  138,  132,  124,  121,   31,   31,

      120,  119,  118,   31,  115,   31,   32,  143,  113,   32,
       32,  143,  105,   98,   32,   32,  143,  152,  143,  143,
      143,  152,  174,   32,   32,   89,  152,   87,  152,  152,
      152,  174,   85,  174,  174,  174,   83,   82,   72,   69,
       66,   63,   61,   60,   59,   58,   32,   32,   55,   51,
       45,   32,   33,   32,   39,   39,   39,   25,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,

       39,   39,   41,   41,   18,    3,   41,   41,   41,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   41,   41,   41,   62,    0,    0,
       62,   62,    0,    0,    0,   62,   62,    0,    0,    0,
        0,    0,    0,    0,   62,   62,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   62,   62,    0,
        0,    0,   62,    0,   62,   65,    0,    0,   65,   65,
        0,    0,    0,   65,   65,    0,    0,    0,    0,    0,

        0,    0,   65,   65,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   65,   65,    0,    0,    0,
       65,    0,   65,   68,    0,    0,   68,   68,    0,    0,
        0,   68,   68,    0,    0,    0,    0,    0,    0,    0,
       68,   68,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   68,   68,    0,    0,    0,   68,    0,
       68,   71,    0,    0,   71,   71,    0,    0,    0,   71,
       71,    0,    0,    0,    0,    0,    0,    0,   71,   71,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   71,   71,    0,    0,    0,   71,    0,   71,   78,
       78,   78,    0,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,

       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   95,   95,   95,    0,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,  109,  109,  109,    0,  109,  109,  109,
      109,  109,  109,    0,  109,  109,  109,    0,    0,    0,
      109,  109,  109,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  109,  109,  109,    0,    0,  109,  109,
      109,  110,  110,  110,    0,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  111,
      111,  111,    0,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,

      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  207,  207,  207,  208,  208,  208,    0,    0,
      208,  209,  209,  209,    0,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  210,  210,  210,  210,
      210,    0,  210,  210,  210,    0,  210,  210,  211,  211,
      211,    0,  211,  211,  211,  211,  211,  211,  211,  211,
      211,  211,  211,  212,  212,  212,    0,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  213,  213,

      213,    0,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  214,  214,  214,    0,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  215,  215,
      215,  215,    0,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,    0,  216,  216,  216,  216,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,    0,
      217,  217,  217,  218,  218,    0,  218,    0,  218,  218,
      218,  218,    0,  218,  218,  219,  219,    0,  219,    0,
        0,  219,  219,  219,  219,  219,  219,  220,  220,    0,

      220,    0,    0,  220,  220,  220,    0,  220,  220,  220,
      221,  221,    0,  221,    0,    0,  221,  221,  221,    0,
      221,  221,    0,  221,  222,  222,    0,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  223,
      223,    0,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  224,  224,    0,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  225,
        0,  225,    0,    0,  225,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,

      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#define INITIAL 0
/*      -*- OpenSAF  -*-
 *
 * (C) Copyright 2008 The OpenSAF Foundation
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
 * under the GNU Lesser General Public License Version 2.1, February 1999.
 * The complete license can be accessed from the following location:
 * http://opensource.org/licenses/lgpl-license.php
 * See the Copying file included with the OpenSAF distribution for full
 * licensing terms.
 *
 * Author(s): Emerson Network Power
 *
 */

/*****************************************************************************
 MODULE NAME:  CLILEX.L
..............................................................................

  DESCRIPTION:

  Lexer file for tokenising the input

******************************************************************************
*/

/*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

                Common Include Files.

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*/
#include "cli.h"

/*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                        Variable declaration.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*/
static CLI_CB *lexCli = 0;
EXTERN_C int32 yylineno;

#define m_CHECK_CONTINOUS_EXP_ERR() \
{\
    if(0 == lexCli->par_cb.grpCntr &&\
       TRUE == lexCli->par_cb.cont_expFlag)\
    {\
        par_log_error(CLI_TOK_CONTINOUS_EXP);\
        lexCli->par_cb.errFlag = TRUE;\
    }\
}

/*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                        Token declaration.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*/
/*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                               Token Action.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*/

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif
#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite(yytext, yyleng, 1, yyout)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
{ \
  int32 size;\
                      \
  if(CLI_CMD_BUFFER == lexCli->par_cb.bfrType)\
  {\
      size = strlen(lexCli->par_cb.ipbuffer);\
      if(size < max_size)\
      {\
          memset(buf, 0, max_size);\
          strcpy(buf, lexCli->par_cb.ipbuffer);\
          memset(lexCli->par_cb.ipbuffer, 0, size);\
          result = size;\
      }\
  }\
  else if (CLI_FILE_BUFFER == lexCli->par_cb.bfrType &&\
  ((result = fread( buf, 1, max_size, yyin )) == 0) \
           && ferror( yyin ) ) \
      YY_FATAL_ERROR( "input in flex scanner failed");\
}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
extern int yylex YY_PROTO(( void ));
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
    YY_USER_ACTION

YY_DECL
    {
    register yy_state_type yy_current_state;
    register char *yy_cp = NULL, *yy_bp = NULL;
    register int yy_act;

    size_t ret;


    if ( yy_init )
        {
        yy_init = 0;

#ifdef YY_USER_INIT
        YY_USER_INIT;
#endif

        if ( ! yy_start )
            yy_start = 1;    /* first start state */

        if ( ! yyin )
            yyin = stdin;

        if ( ! yyout )
            yyout = stdout;

        if ( ! yy_current_buffer )
            yy_current_buffer =
                yy_create_buffer( yyin, YY_BUF_SIZE );

        yy_load_buffer_state();
        }

    while ( 1 )        /* loops until end-of-file is reached */
        {
        yy_cp = yy_c_buf_p;

        /* Support of yytext. */
        *yy_cp = yy_hold_char;

        /* yy_bp points to the position in yy_ch_buf of the start of
         * the current run.
         */
        yy_bp = yy_cp;

        yy_current_state = yy_start;
yy_match:
        do
            {
            register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
            if ( yy_accept[yy_current_state] )
                {
                yy_last_accepting_state = yy_current_state;
                yy_last_accepting_cpos = yy_cp;
                }
            while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
                {
                yy_current_state = (int) yy_def[yy_current_state];
                if ( yy_current_state >= 205 )
                    yy_c = yy_meta[(unsigned int) yy_c];
                }
            yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
            ++yy_cp;
            }
        while ( yy_base[yy_current_state] != 1376 );

yy_find_action:
        yy_act = yy_accept[yy_current_state];
        if ( yy_act == 0 )
            { /* have to back up */
            yy_cp = yy_last_accepting_cpos;
            yy_current_state = yy_last_accepting_state;
            yy_act = yy_accept[yy_current_state];
            }

        YY_DO_BEFORE_ACTION;


do_action:    /* This label is used only to access EOF actions. */


        switch ( yy_act )
    { /* beginning of action switch */
            case 0: /* must back up */
            /* undo the effects of YY_DO_BEFORE_ACTION */
            *yy_cp = yy_hold_char;
            yy_cp = yy_last_accepting_cpos;
            yy_current_state = yy_last_accepting_state;
            goto yy_find_action;

case 1:
YY_RULE_SETUP
{
                    /* token - Parameter (wildcard) */
                    m_CHECK_CONTINOUS_EXP_ERR();
                    
                    lexCli->par_cb.chCnt += strlen(yytext);
                    if(CLI_COMMAND_MODE == lexCli->par_cb.mode)
                        return (CLI_TOK_WILDCARD);
                }
    YY_BREAK
case 2:
YY_RULE_SETUP
{
                    /* token - Parameter (MacAddress) */
                    m_CHECK_CONTINOUS_EXP_ERR();
                    
                    lexCli->par_cb.chCnt += strlen(yytext);
                    if(CLI_COMMAND_MODE == lexCli->par_cb.mode)
                        return (CLI_TOK_MACADDR);
                }
    YY_BREAK
case 3:
YY_RULE_SETUP
{
                    /* token - Parameter (Ipv4Address/Ipv4Mask) */
                    m_CHECK_CONTINOUS_EXP_ERR();
                    
                    lexCli->par_cb.chCnt += strlen(yytext);
                    if(CLI_COMMAND_MODE == lexCli->par_cb.mode)
                        return (CLI_TOK_COMMUNITY);
                }
    YY_BREAK
case 4:
case 5:
YY_RULE_SETUP
{
                    /* token - Parameter (Ipv4Address/Ipv4Mask) */
                    m_CHECK_CONTINOUS_EXP_ERR();
                    
                    lexCli->par_cb.chCnt += strlen(yytext);
                    if(CLI_COMMAND_MODE == lexCli->par_cb.mode)
                        return (CLI_TOK_CIDRv4);
                }
    YY_BREAK
case 6:
case 7:
YY_RULE_SETUP
{
                    /* token - Parameter(IP-Addressv6) */
                    m_CHECK_CONTINOUS_EXP_ERR();
                    
                    lexCli->par_cb.chCnt += strlen(yytext);                            
                    if(CLI_COMMAND_MODE == lexCli->par_cb.mode)
                        return (CLI_TOK_IPADDRv6);
                }   
    YY_BREAK
case 8:
case 9:
case 10:
YY_RULE_SETUP
{
                    /* token - Parameter(IP-Addressv4) */
                    m_CHECK_CONTINOUS_EXP_ERR();
                    
                    lexCli->par_cb.chCnt += strlen(yytext);
                    if(CLI_COMMAND_MODE == lexCli->par_cb.mode)
                        return (CLI_TOK_IPADDRv4);
                }
    YY_BREAK
case 11:
case 12:
YY_RULE_SETUP
{
                    /* token - Parameter(IP-Address Maskv4) */
                    m_CHECK_CONTINOUS_EXP_ERR();
                    
                    lexCli->par_cb.chCnt += strlen(yytext);                 
                    return (CLI_TOK_MASKv4);
                }
    YY_BREAK
case 13:
case 14:
YY_RULE_SETUP
{
                    /* token - Parameter(IP-Address Maskv6) */
                    m_CHECK_CONTINOUS_EXP_ERR();
                    
                    lexCli->par_cb.chCnt += strlen(yytext);
                    return (CLI_TOK_CIDRv6);
                }                      
    YY_BREAK
case 15:
case 16:
YY_RULE_SETUP
{
                    /* token - Parameter(Number) */                    
                    m_CHECK_CONTINOUS_EXP_ERR();
                    
                    lexCli->par_cb.chCnt += strlen(yytext);
                    if(CLI_COMMAND_MODE == lexCli->par_cb.mode)
                        return (CLI_TOK_NUMBER);                        
                }
    YY_BREAK
case 17:
YY_RULE_SETUP
{ 
                    /* token - Keyword  */
                    /* A keyword is any sequence of characters in 
                       lower case */
                    m_CHECK_CONTINOUS_EXP_ERR();
                       
                    lexCli->par_cb.chCnt += strlen(yytext);   
                    if(CLI_COMMAND_MODE == lexCli->par_cb.mode)
                        return (CLI_TOK_KEYWORD);                   
                }
    YY_BREAK
case 18:
YY_RULE_SETUP
{
                    /* token - Password */
                    /* A alfha numeric characters */
                    lexCli->par_cb.chCnt += strlen(yytext);
                    if(CLI_COMMAND_MODE == lexCli->par_cb.mode)
                        return (CLI_TOK_PASSWORD);              
                }               
    YY_BREAK
case 19:
YY_RULE_SETUP
{   
                    /* token - Parameter(String) */
                    /* A string parameter is any sequrnce of characters
                       in upper case */
                    m_CHECK_CONTINOUS_EXP_ERR();
                       
                    lexCli->par_cb.chCnt += strlen(yytext);   
                    if(CLI_COMMAND_MODE == lexCli->par_cb.mode)
                        return (CLI_TOK_PARAM);                 
                }               
    YY_BREAK
case 20:
YY_RULE_SETUP
{
                    /* token - Range */ 
                    lexCli->par_cb.chCnt += strlen(yytext);
                    return (CLI_TOK_RANGE);
                }
    YY_BREAK
case 21:
YY_RULE_SETUP
{
                    /* Default value associated with the token */
                    lexCli->par_cb.chCnt += strlen(yytext);
                    return(CLI_TOK_DEFAULT_VAL);
                }
    YY_BREAK
case 22:
YY_RULE_SETUP
{               
                    /* Help string associated with the token */
                    lexCli->par_cb.chCnt += strlen(yytext);                    
                    return (CLI_TOK_HELP_STR);
                }
    YY_BREAK
case 23:
YY_RULE_SETUP
{
                    /* Node change string associated with the token */              
                    lexCli->par_cb.chCnt += strlen(yytext);
                    return (CLI_TOK_MODE_CHANGE);
                }
    YY_BREAK
case 24:
YY_RULE_SETUP
{
                    /* Continous Expression */                      
                    m_CHECK_CONTINOUS_EXP_ERR();
                    
                    if(NCSCLI_GROUP != 
                        lexCli->par_cb.tokList[lexCli->par_cb.tokCnt-1]->tokType)                    
                    {
                        par_log_error(CLI_TOK_CONTINOUS_EXP);       
                        lexCli->par_cb.errFlag = TRUE;
                    }
                    lexCli->par_cb.chCnt += strlen(yytext);
                    lexCli->par_cb.cont_expFlag = TRUE;
                    return (CLI_TOK_CONTINOUS_EXP);             
                }
    YY_BREAK
case 25:
YY_RULE_SETUP
{
                    /* token - white space */                       
                    lexCli->par_cb.chCnt += strlen(yytext);
                    ; /* ignore white space */
                }
    YY_BREAK
case 26:
YY_RULE_SETUP
{
                    /* token - Carrage return */                    
                    ; /* ignore carrage return */
                }              
    YY_BREAK
case 27:
YY_RULE_SETUP
{                                          
                    /* End of Command */               
                    if(0 != lexCli->par_cb.grpCntr)
                    {
                        lexCli->par_cb.errFlag = TRUE;                        
                        par_log_error(CLI_TOK_LCURLYBRACE);     
                    }
                    
                    if(0 != lexCli->par_cb.optCntr)
                    {
                        lexCli->par_cb.errFlag = TRUE;
                        par_log_error(CLI_TOK_LBRACE);      
                    }
                    
                    if(FALSE == lexCli->par_cb.errFlag)
                    {
                        uns32   Index = 0;
                        for(Index=0; Index<lexCli->par_cb.tokCnt; Index++)
                        {
                            cli_scan_token(lexCli, lexCli->par_cb.tokList[Index],
                                lexCli->par_cb.tokList[Index]->tokRel);
                        }
                        
                        cli_set_token_attrib(lexCli, lexCli->par_cb.tokList[lexCli->par_cb.tokCnt - 1],
                                             CLI_DO_FUNC, "do function for the command");                                                                 
                        lexCli->par_cb.tokCnt = 0;                        
                    }
                    else
                    {
                        uns32   Index = 0;
                        for(Index=0; Index<lexCli->par_cb.tokCnt; Index++)
                            cli_free_cmd_element(&lexCli->par_cb.tokList[Index]);
                            
                        lexCli->par_cb.tokCnt = 0; 
                        lexCli->par_cb.errFlag = FALSE;                        
                    }
                    
                    /* reset all counter that are being used by yacc
                           at the end of command */                                                                             
                    lexCli->par_cb.chCnt = 0;
                    lexCli->par_cb.errPos = 0;  
                    lexCli->par_cb.is_tok_cont = FALSE;
                    lexCli->par_cb.cont_expFlag = FALSE;     
                    lexCli->par_cb.orFlag = FALSE;  
                    lexCli->par_cb.resetLvlFlag = FALSE;
                    lexCli->par_cb.tokLvlCntr = 0;
                    lexCli->par_cb.optLvlCntr = 0;
                    lexCli->par_cb.grpLvlCntr = 0;
                    lexCli->par_cb.optCntr = 0;
                    lexCli->par_cb.optTokCnt = 0;
                    lexCli->par_cb.grpTokCnt = 0;
                    lexCli->par_cb.grpCntr = 0;
                    lexCli->par_cb.grpStackPtr = -1;                
                    lexCli->par_cb.optStackPtr = -1;
                    lexCli->par_cb.brcStackPtr = -1;
                    lexCli->par_cb.brcType = CLI_NONE_BRACE;    

                    m_LOG_NCSCLI_HEADLINE(NCSCLI_HDLN_CLI_NEWCMD);

                }               
    YY_BREAK
case 28:
YY_RULE_SETUP
{
                    /* token - Group start brace */
                    m_CHECK_CONTINOUS_EXP_ERR();
                    
                    lexCli->par_cb.chCnt += strlen(yytext);
                    return (CLI_TOK_LCURLYBRACE);
                }                           
    YY_BREAK
case 29:
YY_RULE_SETUP
{
                    /* token - Group end brace */                    
                    lexCli->par_cb.chCnt += strlen(yytext);
                    return (CLI_TOK_RCURLYBRACE);
                }   
    YY_BREAK
case 30:
YY_RULE_SETUP
{
                    /* token - Optional start brace */
                    m_CHECK_CONTINOUS_EXP_ERR();
                    
                    lexCli->par_cb.chCnt += strlen(yytext);
                    return (CLI_TOK_LBRACE);
                }                           
    YY_BREAK
case 31:
YY_RULE_SETUP
{
                    /* token - Optional end brace */                                                                
                    lexCli->par_cb.chCnt += strlen(yytext);
                    return (CLI_TOK_RBRACE);                    
                }                                           
    YY_BREAK
case 32:
YY_RULE_SETUP
{
                    /* token - or */ 
                    if(lexCli->par_cb.grpCntr == 0 && lexCli->par_cb.cont_expFlag) 
                        lexCli->par_cb.cont_expFlag = FALSE; 
                    lexCli->par_cb.chCnt += strlen(yytext);
                    return (CLI_TOK_OR);
                }
    YY_BREAK
case 33:
YY_RULE_SETUP
{
                    /* token - Less than */
                    m_CHECK_CONTINOUS_EXP_ERR();
                    
                    lexCli->par_cb.chCnt += strlen(yytext);
                    return (CLI_TOK_LESS_THAN);
                }
    YY_BREAK
case 34:
YY_RULE_SETUP
{
                    /* token - Greater than */                    
                    lexCli->par_cb.chCnt += strlen(yytext);
                    return (CLI_TOK_GRTR_THAN);
                }
    YY_BREAK
case 35:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
{
                    /* token - Error for unterminated range delimiter*/
                    par_log_error(CLI_TOK_RANGE);       
                    lexCli->par_cb.errFlag = TRUE;
                }
    YY_BREAK
case 36:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
{
                    /* token - Error for unterminated default value delimiter */
                    par_log_error(CLI_TOK_DEFAULT_VAL);     
                    lexCli->par_cb.errFlag = TRUE;
                }
    YY_BREAK
case 37:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
{
                    /* token - Error for unterminated mode delimiter */
                    par_log_error(CLI_TOK_MODE_CHANGE);     
                    lexCli->par_cb.errFlag = TRUE;
                }               
    YY_BREAK
case 38:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
{
                    /* token - Error for unterminated help delimiter */
                    par_log_error(CLI_TOK_HELP_STR);
                    lexCli->par_cb.errFlag = TRUE;
                }              
    YY_BREAK
case 39:
YY_RULE_SETUP
ret=ECHO;
    YY_BREAK
case YY_STATE_EOF(INITIAL):
    yyterminate();

    case YY_END_OF_BUFFER:
        {
        /* Amount of text matched not including the EOB char. */
        int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

        /* Undo the effects of YY_DO_BEFORE_ACTION. */
        *yy_cp = yy_hold_char;
        YY_RESTORE_YY_MORE_OFFSET

        if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
            {
            /* We're scanning a new file or input source.  It's
             * possible that this happened because the user
             * just pointed yyin at a new source and called
             * yylex().  If so, then we have to assure
             * consistency between yy_current_buffer and our
             * globals.  Here is the right place to do so, because
             * this is the first action (other than possibly a
             * back-up) that will match for the new input source.
             */
            yy_n_chars = yy_current_buffer->yy_n_chars;
            yy_current_buffer->yy_input_file = yyin;
            yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
            }

        /* Note that here we test for yy_c_buf_p "<=" to the position
         * of the first EOB in the buffer, since yy_c_buf_p will
         * already have been incremented past the NUL character
         * (since all states make transitions on EOB to the
         * end-of-buffer state).  Contrast this with the test
         * in input().
         */
        if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
            { /* This was really a NUL. */
            yy_state_type yy_next_state;

            yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

            yy_current_state = yy_get_previous_state();

            /* Okay, we're now positioned to make the NUL
             * transition.  We couldn't have
             * yy_get_previous_state() go ahead and do it
             * for us because it doesn't know how to deal
             * with the possibility of jamming (and we don't
             * want to build jamming into it because then it
             * will run more slowly).
             */

            yy_next_state = yy_try_NUL_trans( yy_current_state );

            yy_bp = yytext_ptr + YY_MORE_ADJ;

            if ( yy_next_state )
                {
                /* Consume the NUL. */
                yy_cp = ++yy_c_buf_p;
                yy_current_state = yy_next_state;
                goto yy_match;
                }

            else
                {
                yy_cp = yy_c_buf_p;
                goto yy_find_action;
                }
            }

        else switch ( yy_get_next_buffer() )
            {
            case EOB_ACT_END_OF_FILE:
                {
                yy_did_buffer_switch_on_eof = 0;

                if ( yywrap() )
                    {
                    /* Note: because we've taken care in
                     * yy_get_next_buffer() to have set up
                     * yytext, we can now set up
                     * yy_c_buf_p so that if some total
                     * hoser (like flex itself) wants to
                     * call the scanner after we return the
                     * YY_NULL, it'll still work - another
                     * YY_NULL will get returned.
                     */
                    yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

                    yy_act = YY_STATE_EOF(YY_START);
                    goto do_action;
                    }

                else
                    {
                    if ( ! yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;
                    }
                break;
                }

            case EOB_ACT_CONTINUE_SCAN:
                yy_c_buf_p =
                    yytext_ptr + yy_amount_of_matched_text;

                yy_current_state = yy_get_previous_state();

                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_match;

            case EOB_ACT_LAST_MATCH:
                yy_c_buf_p =
                &yy_current_buffer->yy_ch_buf[yy_n_chars];

                yy_current_state = yy_get_previous_state();

                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_find_action;
            }
        break;
        }

    default:
        YY_FATAL_ERROR(
            "fatal flex scanner internal error--no action found" );
    } /* end of action switch */
        } /* end of scanning one token */
    } /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *    EOB_ACT_LAST_MATCH -
 *    EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *    EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
    {
    register char *dest = yy_current_buffer->yy_ch_buf;
    register char *source = yytext_ptr;
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
        YY_FATAL_ERROR(
        "fatal flex scanner internal error--end of buffer missed" );

    if ( yy_current_buffer->yy_fill_buffer == 0 )
        { /* Don't try to fill the buffer, so this is an EOF. */
        if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
            {
            /* We matched a single character, the EOB, so
             * treat this as a final EOF.
             */
            return EOB_ACT_END_OF_FILE;
            }

        else
            {
            /* We matched some text prior to the EOB, first
             * process it.
             */
            return EOB_ACT_LAST_MATCH;
            }
        }

    /* Try to read more data. */

    /* First move last chars to start of buffer. */
    number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

    for ( i = 0; i < number_to_move; ++i )
        *(dest++) = *(source++);

    if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
        /* don't do the read, it's not guaranteed to return an EOF,
         * just force an EOF
         */
        yy_current_buffer->yy_n_chars = yy_n_chars = 0;

    else
        {
        int num_to_read =
            yy_current_buffer->yy_buf_size - number_to_move - 1;

        while ( num_to_read <= 0 )
            { /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
            YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

            /* just a shorter name for the current buffer */
            YY_BUFFER_STATE b = yy_current_buffer;

            int yy_c_buf_p_offset =
                (int) (yy_c_buf_p - b->yy_ch_buf);

            if ( b->yy_is_our_buffer )
                {
                int new_size = b->yy_buf_size * 2;

                if ( new_size <= 0 )
                    b->yy_buf_size += b->yy_buf_size / 8;
                else
                    b->yy_buf_size *= 2;

                b->yy_ch_buf = (char *)
                    /* Include room in for 2 EOB chars. */
                    yy_flex_realloc( (void *) b->yy_ch_buf,
                             b->yy_buf_size + 2 );
                }
            else
                /* Can't grow it, we don't own it. */
                b->yy_ch_buf = 0;

            if ( ! b->yy_ch_buf )
                YY_FATAL_ERROR(
                "fatal error - scanner input buffer overflow" );

            yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

            num_to_read = yy_current_buffer->yy_buf_size -
                        number_to_move - 1;
#endif
            }

        if ( num_to_read > YY_READ_BUF_SIZE )
            num_to_read = YY_READ_BUF_SIZE;

        /* Read in more data. */
        YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
            yy_n_chars, num_to_read );

        yy_current_buffer->yy_n_chars = yy_n_chars;
        }

    if ( yy_n_chars == 0 )
        {
        if ( number_to_move == YY_MORE_ADJ )
            {
            ret_val = EOB_ACT_END_OF_FILE;
            yyrestart( yyin );
            }

        else
            {
            ret_val = EOB_ACT_LAST_MATCH;
            yy_current_buffer->yy_buffer_status =
                YY_BUFFER_EOF_PENDING;
            }
        }

    else
        ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

    return ret_val;
    }


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
    {
    register yy_state_type yy_current_state;
    register char *yy_cp;

    yy_current_state = yy_start;

    for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
        {
        register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
        if ( yy_accept[yy_current_state] )
            {
            yy_last_accepting_state = yy_current_state;
            yy_last_accepting_cpos = yy_cp;
            }
        while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
            {
            yy_current_state = (int) yy_def[yy_current_state];
            if ( yy_current_state >= 205 )
                yy_c = yy_meta[(unsigned int) yy_c];
            }
        yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
        }

    return yy_current_state;
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *    next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
    {
    register int yy_is_jam;
    register char *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
        {
        yy_last_accepting_state = yy_current_state;
        yy_last_accepting_cpos = yy_cp;
        }
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
        {
        yy_current_state = (int) yy_def[yy_current_state];
        if ( yy_current_state >= 205 )
            yy_c = yy_meta[(unsigned int) yy_c];
        }
    yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
    yy_is_jam = (yy_current_state == 204);

    return yy_is_jam ? 0 : yy_current_state;
    }


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
    {
    int c;

    *yy_c_buf_p = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
        {
        /* yy_c_buf_p now points to the character we want to return.
         * If this occurs *before* the EOB characters, then it's a
         * valid NUL; if not, then we've hit the end of the buffer.
         */
        if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
            /* This was really a NUL. */
            *yy_c_buf_p = '\0';

        else
            { /* need more input */
            int offset = yy_c_buf_p - yytext_ptr;
            ++yy_c_buf_p;

            switch ( yy_get_next_buffer() )
                {
                case EOB_ACT_LAST_MATCH:
                    /* This happens because yy_g_n_b()
                     * sees that we've accumulated a
                     * token and flags that we need to
                     * try matching the token before
                     * proceeding.  But for input(),
                     * there's no matching to consider.
                     * So convert the EOB_ACT_LAST_MATCH
                     * to EOB_ACT_END_OF_FILE.
                     */

                    /* Reset buffer status. */
                    yyrestart( yyin );

                    /* fall through */

                case EOB_ACT_END_OF_FILE:
                    {
                    if ( yywrap() )
                        return EOF;

                    if ( ! yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;
#ifdef __cplusplus
                    return yyinput();
#else
                    return input();
#endif
                    }

                case EOB_ACT_CONTINUE_SCAN:
                    yy_c_buf_p = yytext_ptr + offset;
                    break;
                }
            }
        }

    c = *(unsigned char *) yy_c_buf_p;    /* cast for 8-bit char's */
    *yy_c_buf_p = '\0';    /* preserve yytext */
    yy_hold_char = *++yy_c_buf_p;


    return c;
    }
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
    {
    if ( ! yy_current_buffer )
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
    {
    if ( yy_current_buffer == new_buffer )
        return;

    if ( yy_current_buffer )
        {
        /* Flush out information for old buffer. */
        *yy_c_buf_p = yy_hold_char;
        yy_current_buffer->yy_buf_pos = yy_c_buf_p;
        yy_current_buffer->yy_n_chars = yy_n_chars;
        }

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* We don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
    if ( ! b )
        YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
    if ( ! b->yy_ch_buf )
        YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_is_our_buffer = 1;

    yy_init_buffer( b, file );

    return b;
    }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
    {
    if ( ! b )
        return;

    if ( b == yy_current_buffer )
        yy_current_buffer = (YY_BUFFER_STATE) 0;

    if ( b->yy_is_our_buffer )
        yy_flex_free( (void *) b->yy_ch_buf );

    yy_flex_free( (void *) b );
    }



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


    {
    yy_flush_buffer( b );

    b->yy_input_file = file;
    b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
    b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
    b->yy_is_interactive = 0;
#else
    b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
    }


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

    {
    if ( ! b )
        return;

    b->yy_n_chars = 0;

    /* We always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[0];

    b->yy_at_bol = 1;
    b->yy_buffer_status = YY_BUFFER_NEW;

    if ( b == yy_current_buffer )
        yy_load_buffer_state();
    }


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
    {
    YY_BUFFER_STATE b;

    if ( size < 2 ||
         base[size-2] != YY_END_OF_BUFFER_CHAR ||
         base[size-1] != YY_END_OF_BUFFER_CHAR )
        /* They forgot to leave room for the EOB's. */
        return 0;

    b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
    if ( ! b )
        YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

    b->yy_buf_size = size - 2;    /* "- 2" to take care of EOB's */
    b->yy_buf_pos = b->yy_ch_buf = base;
    b->yy_is_our_buffer = 0;
    b->yy_input_file = 0;
    b->yy_n_chars = b->yy_buf_size;
    b->yy_is_interactive = 0;
    b->yy_at_bol = 1;
    b->yy_fill_buffer = 0;
    b->yy_buffer_status = YY_BUFFER_NEW;

    yy_switch_to_buffer( b );

    return b;
    }
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
    {
    int len;
    for ( len = 0; yy_str[len]; ++len )
        ;

    return yy_scan_bytes( yy_str, len );
    }
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
    {
    YY_BUFFER_STATE b;
    char *buf;
    yy_size_t n;
    int i;

    /* Get memory for full buffer, including space for trailing EOB's. */
    n = len + 2;
    buf = (char *) yy_flex_alloc( n );
    if ( ! buf )
        YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

    for ( i = 0; i < len; ++i )
        buf[i] = bytes[i];

    buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

    b = yy_scan_buffer( buf, n );
    if ( ! b )
        YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

    /* It's okay to grow etc. this buffer, and we should throw it
     * away when we're done.
     */
    b->yy_is_our_buffer = 1;

    return b;
    }
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
    {
    if ( yy_start_stack_ptr >= yy_start_stack_depth )
        {
        yy_size_t new_size;

        yy_start_stack_depth += YY_START_STACK_INCR;
        new_size = yy_start_stack_depth * sizeof( int );

        if ( ! yy_start_stack )
            yy_start_stack = (int *) yy_flex_alloc( new_size );

        else
            yy_start_stack = (int *) yy_flex_realloc(
                    (void *) yy_start_stack, new_size );

        if ( ! yy_start_stack )
            YY_FATAL_ERROR(
            "out of memory expanding start-condition stack" );
        }

    yy_start_stack[yy_start_stack_ptr++] = YY_START;

    BEGIN(new_state);
    }
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
    {
    if ( --yy_start_stack_ptr < 0 )
        YY_FATAL_ERROR( "start-condition stack underflow" );

    BEGIN(yy_start_stack[yy_start_stack_ptr]);
    }
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
    {
    return yy_start_stack[yy_start_stack_ptr - 1];
    }
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
    {
    (void) fprintf( stderr, "%s\n", msg );
    exit( YY_EXIT_FAILURE );
    }



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
    do \
        { \
        /* Undo effects of setting up yytext. */ \
        yytext[yyleng] = yy_hold_char; \
        yy_c_buf_p = yytext + n; \
        yy_hold_char = *yy_c_buf_p; \
        *yy_c_buf_p = '\0'; \
        yyleng = n; \
        } \
    while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
    {
    register int i;
    for ( i = 0; i < n; ++i )
        s1[i] = s2[i];
    }
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
    {
    register int n;
    for ( n = 0; s[n]; ++n )
        ;

    return n;
    }
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
    {
    return (void *) malloc( size );
    }

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
    {
    /* The cast to (char *) in the following accommodates both
     * implementations that use char* generic pointers, and those
     * that use void* generic pointers.  It works with the latter
     * because both ANSI C and C++ allow castless assignment from
     * any pointer type to void*, and deal with argument conversions
     * as though doing an assignment.
     */
    return (void *) realloc( (char *) ptr, size );
    }

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
    {
    free( ptr );
    }

#if YY_MAIN
int main()
    {
    yylex();
    return 0;
    }
#endif


/*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                            Lexer Functions.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*/
int yywrap(void)
{
    return 1;
}

void cli_lcb_set(CLI_CB *pCli)
{
    lexCli = pCli;  
}
 
void par_log_error(uns32 sel)
{
    switch(sel) {
    case CLI_TOK_RANGE:
        lexCli->par_cb.errPos = (uns16)lexCli->par_cb.chCnt;      
        sysf_sprintf(lexCli->par_cb.str, "AT POSITION (%d)", lexCli->par_cb.errPos);        
        m_LOG_NCSCLI_COMMENTS(yytext, NCSCLI_PAR_INVALID_RANGE, lexCli->par_cb.str);
        break;    
        
    case CLI_TOK_DEFAULT_VAL:
        lexCli->par_cb.errPos = (uns16)lexCli->par_cb.chCnt;
        sysf_sprintf(lexCli->par_cb.str, "AT POSITION (%d)", lexCli->par_cb.errPos);                            
        m_LOG_NCSCLI_COMMENTS(yytext, NCSCLI_PAR_INVALID_DEFVAL, lexCli->par_cb.str);
        break;    
        
    case CLI_TOK_HELP_STR:
        lexCli->par_cb.errPos = (uns16)lexCli->par_cb.chCnt;          
        sysf_sprintf(lexCli->par_cb.str, "AT POSITION (%d)", lexCli->par_cb.errPos);                            
        m_LOG_NCSCLI_COMMENTS(yytext, NCSCLI_PAR_INVALID_HELPSTR, lexCli->par_cb.str);
        break;    
        
    case CLI_TOK_MODE_CHANGE:    
        lexCli->par_cb.errPos = (uns16)lexCli->par_cb.chCnt;                  
        sysf_sprintf(lexCli->par_cb.str, "AT POSITION (%d)", lexCli->par_cb.errPos);        
        m_LOG_NCSCLI_COMMENTS(yytext, NCSCLI_PAR_INVALID_MODECHG, lexCli->par_cb.str);
        break;    
        
    case CLI_TOK_LCURLYBRACE:    
        lexCli->par_cb.errPos = (uns16)lexCli->par_cb.chCnt;      
        sysf_sprintf(lexCli->par_cb.str, "AT POSITION (%d)", lexCli->par_cb.errPos);                
        m_LOG_NCSCLI_COMMENTS(yytext, NCSCLI_PAR_UNTERMINATED_GRPBRACE, lexCli->par_cb.str);
        break;                                              
        
    case CLI_TOK_LBRACE:
        lexCli->par_cb.errPos = (uns16)lexCli->par_cb.chCnt;
        sysf_sprintf(lexCli->par_cb.str, "AT POSITION (%d)", lexCli->par_cb.errPos);        
        m_LOG_NCSCLI_COMMENTS(yytext, NCSCLI_PAR_UNTERMINATED_OPTBRACE, lexCli->par_cb.str);
        break;                                   
    
    case CLI_TOK_CONTINOUS_EXP:
        lexCli->par_cb.errPos = (uns16)lexCli->par_cb.chCnt;
        sysf_sprintf(lexCli->par_cb.str, "AT POSITION (%d)", lexCli->par_cb.errPos);        
        m_LOG_NCSCLI_COMMENTS(yytext, NCSCLI_PAR_INVALID_CONTINOUS_EXP, lexCli->par_cb.str);
        break;           
    }
}

