/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensaf_ais_HandleImpl */

#ifndef _Included_org_opensaf_ais_HandleImpl
#define _Included_org_opensaf_ais_HandleImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensaf_ais_HandleImpl
 * Method:    s_invokeSelect
 * Signature: ([J)V
 */
	JNIEXPORT void JNICALL
	Java_org_opensaf_ais_HandleImpl_s_1invokeSelect___3J(JNIEnv *,
							     jclass,
							     jlongArray);

/*
 * Class:     org_opensaf_ais_HandleImpl
 * Method:    s_invokeSelect
 * Signature: ([JJ)I
 */
	JNIEXPORT jint JNICALL
	Java_org_opensaf_ais_HandleImpl_s_1invokeSelect___3JJ(JNIEnv *,
							      jclass,
							      jlongArray,
							      jlong);

/*
 * Class:     org_opensaf_ais_HandleImpl
 * Method:    checkSelectionObject
 * Signature: (J)Z
 */
	JNIEXPORT jboolean JNICALL
	Java_org_opensaf_ais_HandleImpl_checkSelectionObject(JNIEnv *,
							     jobject,
							     jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_opensaf_ais_SelectionObjectMediator_HandleData */
#ifndef _Included_org_opensaf_ais_SelectionObjectMediator_HandleData
#define _Included_org_opensaf_ais_SelectionObjectMediator_HandleData
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_opensaf_ais_SelectionObjectMediator_Worker */
#ifndef _Included_org_opensaf_ais_SelectionObjectMediator_Worker
#define _Included_org_opensaf_ais_SelectionObjectMediator_Worker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensaf_ais_SelectionObjectMediator_Worker
 * Method:    doSelect
 * Signature: ([II)[I
 */
	JNIEXPORT jintArray JNICALL
	Java_org_opensaf_ais_SelectionObjectMediator_00024Worker_doSelect
	(JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_opensaf_ais_SelectionObjectMediator */
#ifndef _Included_org_opensaf_ais_SelectionObjectMediator
#define _Included_org_opensaf_ais_SelectionObjectMediator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensaf_ais_SelectionObjectMediator
 * Method:    openSocketpair
 * Signature: ()[I
 */
	JNIEXPORT jintArray JNICALL
	Java_org_opensaf_ais_SelectionObjectMediator_openSocketpair(JNIEnv
								    *,
								    jobject);

/*
 * Class:     org_opensaf_ais_SelectionObjectMediator
 * Method:    closeSocketpair
 * Signature: ([I)V
 */
	JNIEXPORT void JNICALL
	Java_org_opensaf_ais_SelectionObjectMediator_closeSocketpair(JNIEnv
								     *,
								     jobject,
								     jintArray);

/*
 * Class:     org_opensaf_ais_SelectionObjectMediator
 * Method:    readSocketpair
 * Signature: (I)I
 */
	JNIEXPORT jint JNICALL
	Java_org_opensaf_ais_SelectionObjectMediator_readSocketpair(JNIEnv
								    *,
								    jobject,
								    jint);

/*
 * Class:     org_opensaf_ais_SelectionObjectMediator
 * Method:    writeSocketpair
 * Signature: (II)V
 */
	JNIEXPORT void JNICALL
	Java_org_opensaf_ais_SelectionObjectMediator_writeSocketpair(JNIEnv
								     *,
								     jobject,
								     jint,
								     jint);

#ifdef __cplusplus
}
#endif
#endif
