#!/usr/bin/env python

import select

from pyosaf.saAis import eSaAisErrorT

from pyosaf.utils import immom
from pyosaf.utils.immoi.implementer import Implementer, AdminOperation
from pyosaf.utils.immom.object import ImmObject
from pyosaf.utils.immom.ccb import Ccb

class_name = "PingPong"
dn         = "pingPongId=1"

class PingPong(Implementer):

    def __init__(self):
        Implementer.__init__(self, class_names=[class_name])

    @AdminOperation(class_name, 0)
    def ping(self, dn, arguments):
        print
        print
        print "Pong!"
        print
        print "INFO: I am %s, received arguments %s" % (dn, arguments)

    @AdminOperation(class_name, 1)
    def pong(self, dn, arguments):
        print 
        print
        print "Ping!"
        print
        print "INFO: I am %s, received arguments %s" % (dn, arguments)


if __name__ == '__main__':

    # Create the ping-pong instance if it doesn't exist
    if not immom.get(dn):

        with Ccb(flags=None) as ccb:
            obj = ImmObject(class_name=class_name, dn=dn)

            obj.pingPongId  = "pingPongId=1"

            ccb.create(obj)

    # Create the implementer instance
    implementer = PingPong()

    # Start dispatch and time update loop
    implementer.enter_dispatch_loop()
