#!/usr/bin/env python

from pyosaf.utils.immoi.implementer import Implementer, Constraints

class Tones(Implementer):

    def __init__(self):
        tone_class_names = ["Do", "Re", "Mi", "Fa", "So", "La", "Ti"]

        Implementer.__init__(self, class_names=tone_class_names,
                             name="TonesImplementer")

        # Set up containment constraints
        constraints = Constraints()

        constraints.add_allowed_containment('Do', 'Re', upper=1)
        constraints.add_allowed_containment('Re', 'Mi', upper=1)
        constraints.add_allowed_containment('Mi', 'Fa', upper=1)
        constraints.add_allowed_containment('Fa', 'So', upper=1)
        constraints.add_allowed_containment('So', 'La', upper=1)
        constraints.add_allowed_containment('La', 'Ti', upper=1)

        self.set_constraints(constraints)

        
if __name__ == "__main__":

    # Create the implementer
    tones_implementer = Tones()

    # Start the infinite dispatch loop
    tones_implementer.enter_dispatch_loop()
