#!/bin/busybox ash
#
#      -*- OpenSAF  -*-
#
# (C) Copyright 2007 The OpenSAF Foundation
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
# under the GNU Lesser General Public License Version 2.1, February 1999.
# The complete license can be accessed from the following location:
# http://opensource.org/licenses/lgpl-license.php
# See the Copying file included with the OpenSAF distribution for full
# licensing terms.
#
# Author(s): Ericsson AB
#

/bin/busybox mount /proc
/bin/busybox --install -s

if grep -q "ubd0=" /proc/cmdline; then
    mkdir -p /newroot
    mknod /dev/ubd0 b 98 0
    mount -t ext2 /dev/ubd0 /newroot
    exec /sbin/switch_root -c /dev/console /newroot /sbin/init
fi

/bin/busybox grep -q runscript /proc/cmdline || exec /sbin/init

/bin/busybox --install -s
mount /sys
mount /dev/shm
mount /tmp
mount /dev/pts
hostdircmd=`tr ' ' '\n' < /proc/cmdline | grep hostdir`
if test -n "$hostdircmd"; then
    dir=`echo $hostdircmd | cut -d '=' -f2`
    mount none /opt -t hostfs -o $dir
fi
runscriptcmd=`tr ' ' '\n' < /proc/cmdline | grep runscript`
if test -n "$runscriptcmd"; then
    script=`echo $runscriptcmd | cut -d '=' -f2`
    test -x $script && exec $script
fi
exec /bin/sh

