#!/bin/bash
#
#           -*- OpenSAF  -*-
# 
# (C) Copyright 2008 The OpenSAF Foundation 
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
# or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
# under the GNU Lesser General Public License Version 2.1, February 1999.
# The complete license can be accessed from the following location:
# http://opensource.org/licenses/lgpl-license.php 
# See the Copying file included with the OpenSAF distribution for full
# licensing terms.
# 
# Author(s): Emerson Network Power
#
#
# Interface Driver startup/shutdown Script
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:
DAEMON=ncs_ifsv_ip_installer
DESC="Interface Learner"
BINPATH=/opt/opensaf/payload/bin
ETCPATH=/opt/opensaf/payload/scripts
PIDLIST=`ps ax | grep $DAEMON | grep -v 'grep' | cut -d" " -f2`

NIDFIFO=/tmp/nodeinit.fifo
NID_MAGIC=AAB49DAA
SERVICE_CODE=IFSVDD

NID_IFSVDD_SUCCESS=1
NID_IFSVDD_CREATE_FAILED=2

stop()
{
  if [ "${PIDLIST}" != "" ]; then
    for i in "${PIDLIST}"; do
       kill -SIGKILL $i  &> /dev/null
       echo "Stopping $DESC: ...[  OK  ]"
    done
  else
    echo -e "There is no $DAEMON running..."
  fi
}

start()
{
   echo -n -e "Starting $DESC: $BINPATH/$DAEMON.. \n";
   start-stop-daemon --start --quiet --exec $BINPATH/$DAEMON 2 & 
   echo ".[  OK  ]";                                     
}

test -f $BINPATH/$DAEMON || exit 0

#set -e

case "$1" in
  start)
        if [ "${PIDLIST}" != "" ]; then 
            echo  "$BINPATH/$DAEMON already running..";
	     else
            start
	    if [ $? != 0 ]; then
               echo "$NID_MAGIC:$SERVICE_CODE:$NID_IFSVDD_CREATE_FAILED" > $NIDFIFO
            else
               echo "$NID_MAGIC:$SERVICE_CODE:$NID_IFSVDD_SUCCESS" > $NIDFIFO
	    fi
        fi;
        ;;
  stop)
        stop
        ;; 

restart|force-reload)
        
        stop
        sleep 1
        start
        ;;
  
*)
        echo "Usage: $ETCPATH/ifsvdemo {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
