#!/bin/bash 
#
#      -*- OpenSAF  -*-
#
# (C) Copyright 2008 The OpenSAF Foundation
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
# under the GNU Lesser General Public License Version 2.1, February 1999.
# The complete license can be accessed from the following location:
# http://opensource.org/licenses/lgpl-license.php
# See the Copying file included with the OpenSAF distribution for full
# licensing terms.
#
# Author(s): Emerson Network Power
#
#
# Name: dhclient
# Date: 2006-03-28
#
#
#echo "START OF DHCLIENT INIT"
#set -vx
#
#NAME=$0
#ARGS=$1
#
#DHCLIENT=/sbin/dhclient
#INTERFACES="bond0 eth3"
#
#case "$ARGS" in
#	start)
#		# CHECK FOR THE EXISTENCE OF THE DHCLIENT COMPONENT
#		pidval=`ps -e -o pid -o args|grep dhclient | grep -v grep | grep -v xterm | grep -v gdb | grep -v ddd | grep -v dhclient-script | grep -v $0 | awk '{print $1}'`
#
#		# IN ABSENCE OF THE DHCLIENT COMPONENT, START IT
#		if [ "$pidval" = "" ] 
#		then
#			${DHCLIENT} ${INTERFACES} &
#		fi
#		;;
#	stop)
#		killall -q -2 dhclient;
#		sleep 1
#		killall -q -9 dhclient;
#		;;
#	*)
#		echo $NAME "start|stop"
#		;;
#esac
#
#echo "END OF DHCLIENT INIT"
#
