#! /bin/sh
#
# (C) Copyright 2009 The OpenSAF Foundation
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
# under the GNU Lesser General Public License Version 2.1, February 1999.
# The complete license can be accessed from the following location:
# http://opensource.org/licenses/lgpl-license.php
# See the Copying file included with the OpenSAF distribution for full
# licensing terms.
#
# Author(s): Ericsson
#

if [ $# -eq 0 ]; then
	echo "usage: `basename $0` <app|comp|csi|csiass|node|sg|si|siass|su|
		|appbasetype|apptype|csbasetype|csiattr|cstype|cluster|
		|compbasetype|compcstype|compglobalattr|comptype|ctcstype|
		|hc|hctype|ng|nodeswbundle|sgbasetype|sgtype|sidep|sirankedsu|
		|subasetype|sutype|sutcomptype|sibasetype|sitype|sitypecstype>"

	exit 1
fi

case "$1" in
	app)
		immfind -c SaAmfApplication
		;;
	comp)
		immfind -c SaAmfComp
		;;
	csi)
		immfind -c SaAmfCSI
		;;
	csiass)
		immfind -c SaAmfCSIAssignment
		;;
	node)
		immfind -c SaAmfNode
		;;
	sg)
		immfind -c SaAmfSG
		;;
	si)
		immfind -c SaAmfSI
		;;
	siass)
		immfind -c SaAmfSIAssignment
		;;
	su)
		immfind -c SaAmfSU
		;;
	appbasetype)
		immfind -c SaAmfAppBaseType
		;;
	apptype)
		immfind -c SaAmfAppType
		;;
	csbasetype)
		immfind -c SaAmfCSBaseType
		;;
	csiattr)
		immfind -c SaAmfCSIAttribute
		;;
	cstype)
		immfind -c SaAmfCSType
		;;
	cluster)
		immfind -c SaAmfCluster
		;;
	compbasetype)
		immfind -c SaAmfCompBaseType
		;;
	compcstype)
		immfind -c SaAmfCompCsType
		;;
	compglobalattr)
		immfind -c SaAmfCompGlobalAttributes
		;;
	comptype)
		immfind -c SaAmfCompType
		;;
	ctcstype)
		immfind -c SaAmfCtCsType
		;;
	hc)
		immfind -c SaAmfHealthcheck
		;;
	hctype)
		immfind -c SaAmfHealthcheckType
		;;
	ng)
		immfind -c SaAmfNodeGroup
		;;
	nodeswbundle)
		immfind -c SaAmfNodeSwBundle
		;;
	sgbasetype)
		immfind -c SaAmfSGBaseType
		;;
	sgtype)
		immfind -c SaAmfSGType
		;;
	sidep)
		immfind -c SaAmfSIDependency
		;;
	sirankedsu)
		 immfind -c SaAmfSIRankedSU
		;;
	subasetype)
		immfind -c SaAmfSUBaseType
		;;
	sutype)
		immfind -c SaAmfSUType
		;;
	sutcomptype)
		immfind -c SaAmfSutCompType
		;;
	sibasetype)
		immfind -c SaAmfSvcBaseType
		;;
	sitype)
		immfind -c SaAmfSvcType
		;;
	sitypecstype)
		immfind -c SaAmfSvcTypeCSTypes
		;;
	*)
		echo "unsupported type, trying anyway..."
		immfind -c $*
		;;
esac

exit $?

