#!/usr/bin/expect --
################################################################################
#
# File:         defaults
# RCS:          $ID: $
# @(#)          $Revision: $
# Description:  Default globals settings
#
#      -*- OpenSAF  -*-
#
# (C) Copyright 2008 The OpenSAF Foundation
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
# under the GNU Lesser General Public License Version 2.1, February 1999.
# The complete license can be accessed from the following location:
# http://opensource.org/licenses/lgpl-license.php
# See the Copying file included with the OpenSAF distribution for full
# licensing terms.
#
# Author(s):
#           Hewlett-Packard Company
#
#
################################################################################

if {![info exists __DEFAULTS_SOURCED] || !$__DEFAULTS_SOURCED } {
   set __DEFAULTS_SOURCED 1
} \
else {
   return 0
}

#***************** Global Variables ************************
set linux_prompt "\[Ll]ogin: "
set login_prompt "\[Ll]ogin: "
set oa_prompt "OA-\[0-9A-Z]\*> "
set root_prompt "# "
set user_prompt "\\\$ "
set ilo_prompt "hpiLO-> "
set user "root"
set passwd "hosehead"
set iloUser "root"
set iloPasswd "hosehead"
set oaUser "root"
set oaPasswd "hosehead"
set domain "saf.telco"
set send_slow {1 .005}
set timeout_setting 60
set connected 0
set atILOprompt 0
set atOAprompt 0
set endl "\[^\r]*\n*\r+\n"
set ws "\[ \t]*"
 # Connect only to iLO or OA
set fwConnect	0

 # TET exit values
set tetExit(PASS)		0
set tetExit(FAIL)		1
set tetExit(UNRESOLVED)	2
set tetExit(NOTINUSE)	3
set tetExit(UNSUPPORTED) 4
set tetExit(UNTESTED)	5
set tetExit(UNINITIATED) 6
set tetExit(NORESULT)	7

 # Debug printing
if {![info exists env(VERBOSE)]} {
	set VERBOSE 0
} else {
	set VERBOSE $env(VERBOSE)
}
if {![info exists env(DRYRUN)]} {
	set DRYRUN 0
} else {
	set DRYRUN $env(DRYRUN)
}

