#!/usr/bin/env python

import select
import argparse

from pyosaf.saAis import eSaAisErrorT

from pyosaf.utils import immom
from pyosaf.utils.immoi.implementer import Implementer, AdminOperationFunction
from pyosaf.utils.immom.object import ImmObject
from pyosaf.utils.immom.ccb import Ccb

class_name = "PingPong"
dn         = "pingPongId=1"


def ping(dn, arguments):
    print
    print
    print "Pong!"
    print

    print "INFO: I am %s, received arguments %s" % (dn, arguments)

    return eSaAisErrorT.SA_AIS_OK


def pong(dn, arguments):
    print 
    print
    print "Ping!"
    print

    print "INFO: I am %s, received arguments %s" % (dn, arguments)

    return eSaAisErrorT.SA_AIS_OK


if __name__ == '__main__':

    # Parse command line arguments
    parser = argparse.ArgumentParser(
        description='Logs and replies to admin operations 0 and 1 towards %s,'
        ' and replies' % dn)

    parser.parse_args()

    # Create the ping-pong instance if it doesn't exist
    if not immom.get(dn):

        with Ccb(flags=None) as ccb:
            obj = ImmObject(class_name=class_name, dn=dn)

            obj.pingPongId  = "pingPongId=1"

            ccb.create(obj)

    # Create the implementer instance
    operations = [AdminOperationFunction(class_name, 0, ping),
                  AdminOperationFunction(class_name, 1, pong)]

    implementer = Implementer(class_names=[class_name])

    implementer.set_admin_operations(operations)

    # Start dispatch and time update loop
    implementer.enter_dispatch_loop()
