#! /bin/ash

#      -*- OpenSAF  -*-
#
#  Copyright (c) 2007, Ericsson AB
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  This
# file and program are licensed under High-Availability Operating 
# Environment Software License Version 1.4.
# Complete License can be accesseble from below location.
# http://www.opensaf.org/license 
# See the Copying file included with the OpenSAF distribution for
# full licensing terms.
#
# Author(s):
#   
#

approot=/opt/aishello/
log=/var/log/cstart.log

errquit() {
    echo "ERROR: $*" >> $log
    exit 1
}

echo "`date`: [cstart $*]" >> $log
test -n "$1" || errquit "No command"
cmd=$1
test -n $2 || errquit "No Application argument"
app=$2

case "$cmd" in
    instantiate)
	application=$approot/bin/$app
	test -x $application || errquit "Application not executable [$application]"
	$application >> $log 2>&1 &
	;;
    terminate)
	killall $app >> $log 2>&1 &
	;;
    cleanup)
	killall $app >> $log 2>&1 &
	;;
    *)
	errquit "Invalid command [$cmd]"
esac
exit 0
