#!/bin/bash
#
# (C) Copyright 2010 The OpenSAF Foundation
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
# under the GNU Lesser General Public License Version 2.1, February 1999.
# The complete license can be accessed from the following location:
# http://opensource.org/licenses/lgpl-license.php
# See the Copying file included with the OpenSAF distribution for full
# licensing terms.
#
# Author(s): Ericsson
#

die() {
    echo "ERROR: $*" >&2
    exit 1
}

verifyExitCode()
{
    if [ $1 -ne 0 ]
    then
       echo "Aborting script! exitCode: $1"
       exit $?
    fi
}


test -f "$PWD/$0" || die 'Must execute $0 from directory where it is located'

if [ -z $1 ] ; then
   RESULTFILE=./imm.xml.`date "+%Y%m%d_%H%M"`
else
   if [ -f $1 ] ; then
      echo "The file $1 already exists"
      exit 1
   fi
  RESULTFILE=$1
fi

SERVICESDIR=./services
TEMP_ROOTDIR=`mktemp -d /tmp/immxml_configure.XXXXXX`
TEMPLATE_TMPDIR=$TEMP_ROOTDIR/templatedir
TMPDIR=$TEMP_ROOTDIR/intermediatefiles
NODE_TMPDIR=$TEMP_ROOTDIR/nodes
LOGFILE=/tmp/$0.log

>$LOGFILE
mkdir -p $TMPDIR
mkdir -p $TEMPLATE_TMPDIR
mkdir -p $NODE_TMPDIR

SC_TEMPLATE=$TEMPLATE_TMPDIR/imm_sc_template.xml
echo -e "merge SC templates to: $SC_TEMPLATE" >> $LOGFILE
./immxml-merge --ignore-missing-class -o $SC_TEMPLATE `find $SERVICESDIR -name \*_sc_template.xml|xargs` >>$LOGFILE 2>&1
verifyExitCode $?

PL_TEMPLATE=$TEMPLATE_TMPDIR/imm_pl_template.xml
echo -e "merge PL templates to: $PL_TEMPLATE" >> $LOGFILE
./immxml-merge --ignore-missing-class -o $PL_TEMPLATE `find $SERVICESDIR -name \*_pl_template.xml|xargs` >>$LOGFILE 2>&1
verifyExitCode $?

echo -e "Generate node specific immxml files into dir:$NODE_TMPDIR" >> $LOGFILE
./immxml-nodegen --nodegen-dir $NODE_TMPDIR --sc-template $SC_TEMPLATE --pl-template $PL_TEMPLATE --node-config ./nodes.cfg >>$LOGFILE 2>&1
verifyExitCode $?

./immxml-merge -o $TMPDIR/imm_classes.xml `find $SERVICESDIR -name \*_classes.xml|xargs` >>$LOGFILE 2>&1
verifyExitCode $?
./immxml-merge --ignore-missing-class -o $TMPDIR/imm_objects.xml `find $SERVICESDIR -name \*_objects.xml|xargs` >>$LOGFILE 2>&1
verifyExitCode $?

# merge all intermediate files to the result file
FILES_TO_MERGE="$SERVICESDIR/imm_copyright.xml $TMPDIR/imm_classes.xml $TMPDIR/imm_objects.xml $NODE_TMPDIR/*.xml"

echo -e "\n Create resulting imm.xml by merging intermediate files :$FILES_TO_MERGE" >> $LOGFILE
./immxml-merge --sort -o $RESULTFILE $FILES_TO_MERGE  >>$LOGFILE 2>&1
verifyExitCode $?

./immxml-validate $RESULTFILE  >>$LOGFILE 2>&1
verifyExitCode $?

rm -rf $TEMP_ROOTDIR

if [ -z $1 ] ; then
   echo "Successfully generated the imm file: $RESULTFILE"
else
   echo "Successfully generated the imm file"
fi

