#!/bin/bash

# MQSV INPUTS
export TET_MQSV_INST_NUM=1
export TET_MQSV_TET_LIST_INDEX=1
export TET_MQSV_TEST_CASE_NUM=-1
export TET_MQSV_NUM_ITER=1
export TET_MQSV_PERS_Q_NAME1=
export TET_MQSV_NON_PERS_Q_NAME1=
export TET_MQSV_ZERO_Q_NAME=
export TET_MQSV_PERS_Q_NAME2=
export TET_MQSV_NON_PERS_Q_NAME2=
export TET_MQSV_Q_GRP_NAME1=
export TET_MQSV_Q_GRP_NAME2=
export TET_MQSV_Q_GRP_NAME3=

# MQSV REDUNDANCY INPUTS
export TET_MQSV_RED_FLAG=
export TET_MQSV_WAIT_TIME=

export MQA_NODE_ID_1=$TET_NODE_ID
export MQA_NODE_ID_2=
export MQA_NODE_ID_3=
