#!/bin/sh
#
#      -*- OpenSAF  -*-
#
# (C) Copyright 2008 The OpenSAF Foundation
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
# under the GNU Lesser General Public License Version 2.1, February 1999.
# The complete license can be accessed from the following location:
# http://opensource.org/licenses/lgpl-license.php
# See the Copying file included with the OpenSAF distribution for full
# licensing terms.
#
# Author(s): Erisson
#

progname=`basename $0`

case "$1" in
	instantiate)
		logger -t $progname "instantiate $SA_AMF_COMPONENT_NAME"
		;;
	cleanup)
		logger -t $progname "cleanup $SA_AMF_COMPONENT_NAME"
		;;
	terminate)
		logger -t $progname "terminate $SA_AMF_COMPONENT_NAME"
		;;
	*)
		echo "Usage: $0 {instantiate|cleanup|terminate}"
		exit 1
esac

exit 0

